### ISSUE TITLE
dist/index.js still broken in the npm package

### ISSUE THREAD

**Issue by gajuro** [mosch/react-avatar-editor#103]
Can you republish the npm package? Thanks.

**Comment by mosch** [comment]
done 4.0.2

**Comment by gajuro** [comment]
@mosch, thanks.

Unfortunately the npm still has an issue.

This time dist/index.js looks fine, but the package.jsom file says the main file is 
"main": "dist/package.umd.js" (https://github.com/mosch/react-avatar-editor/blob/master/package.json#L5)

Had to replace `Editor = require("react-avatar-editor")` with `Editor = require("react-avatar-editor/dist").default` for now.

**Comment by mosch** [comment]
thanks for reporting this

**Comment by oeddyo** [comment]
I got: 

ERROR in ./~/react-avatar-editor/index.js
Module parse failed: /Users/exie/fun/wise-web/node_modules/react-avatar-editor/index.js Unexpected token (413:16)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (413:16)

**Comment by orlandodemauro** [comment]
Hi guys the same for me:

ERROR in ./~/react-avatar-editor/index.js
    Module parse failed: C:\client\node_modules\react-avatar-editor\index.js Line 413: Unexpected token ...
    You may need an appropriate loader to handle this file type.
    |             height: this.getDimensions().canvas.height,
    |             style: {
    |                 ...defaultStyle,
    |                 ...this.props.style
    |             }

I think is related to the babel build.

**Comment by mosch** [comment]
hey. is this stuff fixed for you?

**Comment by LarsMq73** [comment]
I've got the latest 4.1.3 and I don't need the "/dist" any more.
So, I think it's fixed.

Thanks!

**Comment by oeddyo** [comment]
Works for me now! Thanks @mosch !
