### ISSUE TITLE
support react 15.x 

### ISSUE THREAD

**Issue by LarsMq73** [mosch/react-avatar-editor#104]
Hi,

first thanks for this great and easy-to-use avatar editor:)

Is it possible to introduce support for react 15.x?
React already started working on react 16-alpha...

Thanks for a short reply.

LMq

**Comment by mosch** [comment]
this sould be possible with 4.0.2

**Comment by LarsMq73** [comment]
👍  Thx!!!

**Comment by LarsMq73** [comment]
btw / just for info:
this issue also occurs for me:
https://github.com/mosch/react-avatar-editor/issues/103
But I could solve it for now as described there by using the "/dist" in the import...
