### ISSUE TITLE
current released version 4.0.2 uses wrong babel configuration - not ES5 conform

### ISSUE THREAD

**Issue by LarsMq73** [mosch/react-avatar-editor#106]
As I saw, the master version 4.1.2 seems to be corrected.
Please, can you release that version?

Thanks in advance!

LarsMq

**Comment by gato333** [comment]
yup same^
![screen shot 2016-06-23 at 11 45 32 am](https://cloud.githubusercontent.com/assets/7809285/16309802/078316a6-3938-11e6-85d6-87972fc378e9.png)

**Comment by gato333** [comment]
yup same^

**Comment by LarsMq73** [comment]
just a short info:
As I needed a solution, I temporary forked the latest version of the repo and use the forked one within my project, than it works... As soon the origin has been updated I will switch back to the origin
regards

**Comment by mosch** [comment]
you should now be able to use the latest version.

**Comment by LarsMq73** [comment]
thanks, I will try and reply after I got my coffee;)

**Comment by mosch** [comment]
☕ 
![img_2284](https://cloud.githubusercontent.com/assets/224866/16478678/87bf6b40-3e9b-11e6-95f1-2a8a1b3b3d70.JPG)

**Comment by LarsMq73** [comment]
working fine again... Safari opens our app and the editor is working as usual;)
Thanks for that component, cool stuff!
Lars

![screen shot 2016-06-30 at 08 28 44](https://cloud.githubusercontent.com/assets/12513585/16478843/b106e2f2-3e9c-11e6-9f84-92ca2d076972.png)
