### ISSUE TITLE
Allow images to be dragged directly from other applications

### ISSUE THREAD

**Issue by timothyarmes** [mosch/react-avatar-editor#111]
Would it be possible to allow images to be dragged from other apps, such as a web browser, photo library etc.?

**Comment by mosch** [comment]
sure 💯

**Comment by DenizTemizer** [comment]
Works fine together with [react dropzone](https://github.com/okonet/react-dropzone).
Still would be a nice feature for this library.

**Comment by mosch** [comment]
Maybe it's just a good idea to give show how to do it with react-dropzone in the README instead writing the same stuff again…

**Comment by DenizTemizer** [comment]
Plus you would have the benefit to use react-dropzone somewhere else again, if the same code would be included you would still need react-dropzone for different tasks like file upload.

**Comment by mtlewis** [comment]
Now that built-in drag and drop support is gone, maybe this issue can be closed?
