### ISSUE TITLE
Store the blob as jpg

### ISSUE THREAD

**Issue by costaoeste** [mosch/react-avatar-editor#115]
Im using this lib with meteor as backend.
I need to save the avatar as jpg, any idea/snippet/suggest?
Thanks!

**Comment by mosch** [comment]
Hi @costaoeste, have a look at [accessing-the-resulting-image](https://github.com/mosch/react-avatar-editor#accessing-the-resulting-image) 

```js
const canvas = this.refs.editor.getImage()
const jpeg = canvas.toDataURL("image/jpeg", 1.0)
```
