### ISSUE TITLE
Old API restored

### ISSUE THREAD

**Issue by serchavalos** [mosch/react-avatar-editor#116]
Hi @mosch! Here another fan :-)

I believe this merge,  https://github.com/mosch/react-avatar-editor/pull/76, restored an Old API that was already fixed here https://github.com/mosch/react-avatar-editor/pull/63 by @hu9o 

<img width="1640" alt="skarmavbild 2016-10-06 kl 11 52 04" src="https://cloud.githubusercontent.com/assets/587388/19148075/543fda80-8bbb-11e6-87ed-b3d731ceab5b.png">

Was this intentional? If so, please ignore then

Kind regards,

**Comment by hu9o** [comment]
It looks like a mistake on my part!
The old API has been restored in the example file only, right?

**Comment by mosch** [comment]
@hu9o Jip, looks like that. @serchavalos this was by accident, thanks for bringing this up. 

sorry guy, it's my job to pay attention at the PRs 💐

**Comment by serchavalos** [comment]
Np. Thanks for the quick reply

**Comment by mosch** [comment]
fixed that in https://github.com/mosch/react-avatar-editor/commit/471a322babf4f7781bdb4a4c82658fc4a5f89012
