### ISSUE TITLE
Use "files" field in package.json in order to avoid installing unneeded files.

### ISSUE THREAD

**Issue by tkh44** [mosch/react-avatar-editor#117]
For instance by including `.babelrc` in the install you effectively break any usage of the `jsnext:main`.  This is because babel is going to look for those plugins in the local node_modules directory which are not installed when doing `npm install`.

I would submit a pull request, but I'm unsure of what exactly you would want to include in `files`.

**Comment by mosch** [comment]
Hey there,
it's dist/index.js for the package and index.js for the raw. nothing more.

**Comment by mosch** [comment]
@tkh44 so i guess we can close this?
