### ISSUE TITLE
react-avatar-editor with React 15.3.2 generate warnings for all propTypes

### ISSUE THREAD

**Issue by navasiloy** [mosch/react-avatar-editor#119]
This is for scale (the same warnings for other proptypes)
`warning.js:36Warning: You are manually calling a React.PropTypes validation function for the`scale`prop on`AvatarEditor`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.`

Warnings came out with React 15.3.0 and above

**Comment by mosch** [comment]
cannot reproduce this one. can you give more details where this comes from?

**Comment by navasiloy** [comment]
I have just included your component into my project which uses latest react 15.3.2 and react-dom 15.3.2
and got such warnings into console:

![screenshot from 2016-10-27 00-09-01](https://cloud.githubusercontent.com/assets/3064708/19745356/f4e3fb3c-9bd9-11e6-8872-c8a4f0863694.png)

**Comment by navasiloy** [comment]
seems like it's have been fixed now
