### ISSUE TITLE
I am getting CORS error for remote images

### ISSUE THREAD

**Issue by divyenduz** [mosch/react-avatar-editor#12]
I did check that Image() object is given "anonymous value" in https://github.com/mosch/react-avatar-editor/blob/master/index.js#L80 line

But I am still getting the CORS error.

Can you direct me on how to get around it ?

**Comment by mosch** [comment]
I tested it with a remote image and it works. What exact image are you trying to use? Maybe the server permits it by not sending the headers?

**Comment by mosch** [comment]
@divyenduz think this can be closed

**Comment by divyenduz** [comment]
Oops... I missed getting back on this earlier. Sorry, and yes, it was silly on my part. Thanks :)
