### ISSUE TITLE
Prop Errors

### ISSUE THREAD

**Issue by isisAnchalee** [mosch/react-avatar-editor#120]
![image](https://cloud.githubusercontent.com/assets/5697444/19743987/5ea41a34-9b80-11e6-8346-70a8d83d8639.png)

My app was working fine until I checked I ran a new build on it today in which case the avatar editor appears to be exploding. Do you have any idea what is causing this?

**Comment by dan-lee** [comment]
Probably related to https://github.com/mosch/react-avatar-editor/issues/119

**Comment by MtBlue81** [comment]
Hi.
I have same problem, that is 'Uncaught Error: addComponentAsRefTo(...): Only a ReactOwner can have refs....'

I guess that is caused by 'ref' string.
https://facebook.github.io/react/docs/refs-and-the-dom.html
How about fixing it to callback ?

**Comment by mosch** [comment]
@MtBlue81 aww, good one. this could be the thing. let's fix it :-)

**Comment by mosch** [comment]
@MtBlue81 @isisAnchalee would be cool if you guys could verify that fix.
