### ISSUE TITLE
is it possible to add option for enable/disable picture updating?

### ISSUE THREAD

**Issue by betimer** [mosch/react-avatar-editor#124]
Cause I want to use your plugin both for initial display as well as updating.

So when it is initial loaded, I do not want user to manipulate it. Instead, only after user upload new image can they update/zoom their image

**Comment by oyeanuj** [comment]
@mosch I might have a related question. I am slightly unclear on the usage (and happy to make a PR to the Readme if needed) - 

Does the library also have take care of opening the file uploader (and actual upload), or drag/drop? I see methods like `onDropFile` but the example only focuses on an hardcoded image, and nothing in the documentation clarifying it. Or does the library come in after the file has been uploaded?

Apologies if I missed something, maybe it just late at night..

**Comment by hu9o** [comment]
IIRC, react-avatar-editor only listens to the ```drop``` event, and loads the dropped item's URL as an image.
You can see [here](https://github.com/mosch/react-avatar-editor/blob/master/index.js#L431) the code responsible for this.

However, it provides no mechanism to open the file uploader. I happen to have needed this feature in the past, which I implemented rather easily. It involved editing react-avatar-editor's index.js, though:

Added this fragment to the render code:
```jsx
<input type="file" onChange={this.handleSelectFile} />
```

And this method to the component:
```javascript
handleSelectFile(e) {
    e.stopPropagation();
    e.preventDefault();
    var reader = new FileReader();
    reader.onload = (e => this.loadImage(e.target.result));
    reader.readAsDataURL(e.target.files[0]); // get only the first file
},
```

This code is untested, so should you make use of it, I enjoin you to inspect it closely.
Note that you can hide the ugly input and simulate a click on it.

**Comment by mosch** [comment]
@betimer this is up to your implementation! just disable your zoom controls for the start and enable them once a users drops an image!

@oyeanuj also up to the implementation like @hu9o pointed out. does it fix your problem?
