### ISSUE TITLE
a little help to load an image from File obtained from input element.

### ISSUE THREAD

**Issue by javascriptpoet** [mosch/react-avatar-editor#126]
sorry to bug you but i'm kind of stumped. I see i can use the file name for image prop but browser does not give us full path of the File object. I tried converting to dataURL thru fileReader with no luck. Any advise? Thank you. Heres my code:

```
const MyAvatarEditor=createClass({
    propTypes:{
        onChange:PropTypes.function
    },
    getInitialState(){
        return {}
    },
    onImageChange(){
        this.props.onChange(this.refs.editor.getImage())
    },
    onFileLoad(evt){
        const reader = new FileReader();
        reader.onload = (evt)=>{
            this.setState({fileURL:evt.target.result})
        };
        reader.readAsDataURL(evt.target.files[0]);
    },
    render(){
        const {onChange,...otherProps}=this.props;
        return (
            <div>
                <AvatarEditor
                    image={this.state.fileURL}
                    onImageChange={this.onImageChange}
                    ref='editor'
                    width={250}
                    height={250}
                    border={50}
                    color={[255, 255, 255, 0.6]} // RGBA
                    scale={1.2} />
                <input type='file' onChange={this.onFileLoad}/>
            </div>
        )
    }
});
```

**Comment by hu9o** [comment]
How about formatting your code as such ? Your JSX tags are gone.

What does `evt.target.result` evaluates to ? You said you tried to use `dataURL`, but I can't see it in your code.

**Comment by javascriptpoet** [comment]
its line reader.readAsDataURL(evt.target.files[0]); it works thru a callback defined in the line above. sorry about formatting.  the result does come out as dataURL. i checked in the debugger. everything checked out but editor remained black screen. Just let me know what form should an image be.

**Comment by hu9o** [comment]
Can you see your image when you enter the dataUrl in the browser's address bar ?

It's strange because a dataUrl [should work](https://github.com/mosch/react-avatar-editor/issues/80) :/

**Comment by javascriptpoet** [comment]
ok. thanks.I'll give it a try.

**Comment by mosch** [comment]
@javascriptpoet did this solve your problem?
