### ISSUE TITLE
Module parse failed

### ISSUE THREAD

**Issue by yshaish1** [mosch/react-avatar-editor#127]
You may need an appropriate loader to handle this file type.
     height: this.getDimensions().canvas.height,
     style: {
       ...defaultStyle,
       ...this.props.style
     }

I got this message.
what do I need to do to fix that?
thanks.

**Comment by mosch** [comment]
Check out the latest changes here https://github.com/mosch/react-avatar-editor/pull/128 we'll release a new version, can you check that this is fixed than?

**Comment by yshaish1** [comment]
thanks
