### ISSUE TITLE
Zoom to center of Image

### ISSUE THREAD

**Issue by MentalGear** [mosch/react-avatar-editor#131]
As a user, I would expect that when zooming with the slider, the zoom-in would happen on the center of the image, and not the right edge.

**Comment by hu9o** [comment]
I don't understand: The current behaviour seems to be be the one you suggest...

**Comment by MentalGear** [comment]
Nope, unless it's fixed. On chrome on OSX it zoomed-in to the right edge, instead of the center.

**Comment by kuka** [comment]
@MentalGear I use it on Chrome on Sierra and don’t experience that.

**Comment by mosch** [comment]
For me it's not zooming into the center, it zooms like that: http://www.giphy.com/gifs/l3q2VrpoWrjgYjNjW

**Comment by MentalGear** [comment]
@kuka Same configuration as you and mosch, but experiencing the same problem as mosch.

**Comment by kuka** [comment]
I’ve got this https://gfycat.com/FlawedBlushingGermanwirehairedpointer on Chrome 56.

**Comment by mosch** [comment]
maybe the demo is not up to date...

**Comment by mosch** [comment]
thats it. demo not up-to-date. fixed that.
