### ISSUE TITLE
Provide example how to implement pinch-zooming

### ISSUE THREAD

**Issue by MentalGear** [mosch/react-avatar-editor#132]
As a mobile device user, I would expect pinch to zoom to work.
As tested on iOS 9, pinch to zoom is not working.

Also, when using the zoom slider on mobile, the image keeps "jumping" when adjusting zoom levels after dragging the picture.

Hint: Hammer.js is a great touch library to get pinch zoom to work !

**Comment by mosch** [comment]
Zooming is up to the user of react-avatar-editor. We like to keep this simple and small. However we could provide a react-avatar-editor-pinch component that wraps this one and adds support for pinch

**Comment by mosch** [comment]
PR for extra component welcome!

**Comment by innoist** [comment]
I was able to get the Pinch Zoom working by using `react-hammer` library.
So my component looks like this now

` 
  onPinchOut = (e) => {
    console.log('onPinchOut;', e);
      this.setState({ profileImageDroppedScale: this.state.profileImageDroppedScale + 0.1 }) //initial value of 1
   }
  onPinchIn = (e) => {
        this.setState({ profileImageDroppedScale: this.state.profileImageDroppedScale - 0.1 })
    }

//by default pinch is disabled
let options = {
      recognizers: {
        pinch: { enable: true }
      }
    };
           **<Hammer options={options} onPinchIn={this.onPinchIn} onPinchOut={this.onPinchOut}   >
        <div>**
          <AvatarEditor image={this.props.profileImageDropped} width={640} height={640} border={20} ref="avatar" onDrop={this.onDrop} onSave={this.getBase64} onChange onMouseMove={() => {
            event.stopPropagation();
            event.preventDefault()
          }} onMouseUp={() => {
            event.stopPropagation();
            event.preventDefault()
          }} color={[255, 255, 255, 0.7]} // RGBA
            **scale={this.state.profileImageDroppedScale}**
            rotate={this.state.rotate}
          />
        **</div>
      </Hammer>**
  `

it is now working smoothly on touch screens.

**Comment by serabakpak** [comment]
`react-hammerjs` worked great with older versions of React but it doesn't provide support for React 17. Also looks like it isn't actively maintained :(.

Has anyone gotten an alternative way to work with React 17?
