### ISSUE TITLE
Plain loading module doesn't bind it to AvatarEditor

### ISSUE THREAD

**Issue by mb21** [mosch/react-avatar-editor#134]
When including the `dist/index.js` file from https://github.com/mosch/react-avatar-editor/releases/tag/3 in the browser instead of requiring it (I'm using react-rails where require unfortunately isn't available), there are two minor things I needed to change in the `index.js` file:

1. remove `var React=require("react");var ReactDOM=require("react-dom")`
2. change `global.index=mod.exports;` to `global.AvatarEditor=mod.exports;` (this is probably due to the `dist/index.js` having the name `index`

I realize most people use require or something similar, but maybe this can be addressed anyhow..

**Comment by dan-lee** [comment]
I think we should address this problem by delivering an additional webpack bundle.

**Comment by mosch** [comment]
@mb21 do you got exmaples of other libraries that work in your enviroment? im curios about how they export their stuff.

**Comment by mosch** [comment]
closed due inactivity.
