### ISSUE TITLE
Rotate image doesn't work if the aspect ratio isn't a square?

### ISSUE THREAD

**Issue by sakin** [mosch/react-avatar-editor#139]
It seems like if the aspect ratio isn't a square, rotating can cause some issues:

Here is the image by default:
https://www.dropbox.com/s/q8k6qbmd3j5kfwt/Screenshot%202017-02-09%2017.18.59.png?dl=0

Here it is after I've rotated it:
https://www.dropbox.com/s/99ofwh83egk6xpi/Screenshot%202017-02-09%2017.44.01.png?dl=0

As you can see the available space to crop has changed, along with the aspect ratio of the crop. I am following your example, but with non-square dimensions.

If I have done something wrong and this is in fact user error, sorry about that!

**Comment by dan-lee** [comment]
Should be fixed with #144. Can you confirm this?
