### ISSUE TITLE
supporting different values for image cross origin 

### ISSUE THREAD

**Issue by dev-nima** [mosch/react-avatar-editor#142]
Based on https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-crossorigin users can select "anonymous" or "use-credentials" for crossorigin attribute of Images

Allow users to select the cross-origin value for Image:
default value: "anonymous" for supporting previous versions
valid values: '', 'anonymous' or 'use-credentials'

**Comment by dev-nima** [comment]
https://github.com/mosch/react-avatar-editor/pull/141

**Comment by dan-lee** [comment]
@dev-nima v8.0.0 including your PR was just published!
