### ISSUE TITLE
Have the image fit fully inside of canvas onload

### ISSUE THREAD

**Issue by SepiaGroup** [mosch/react-avatar-editor#149]
Currently the image is loaded with the smallest dimension set to the canvas size 

for example if the canvas is set to 500x500 and the image is 640x480 the image will fit within the height and the width will be beyond the crop region. 

can we have an option to set the larger dimension on load?

thanks

**Comment by mosch** [comment]
is this fixed by https://github.com/mosch/react-avatar-editor/issues/150 ?

**Comment by mtlewis** [comment]
No - the default behaviour in the avatar editor is to cover the resulting image with the input image, leaving no white space.  In #152 I changed the behaviour for scale < 1 - previously whenever scale < 1 the image would be scaled correctly (leaving whitespace around it on the resulting image), but could not be moved away from the center.  Now, the image can be dragged around the canvas and all the way to the edges when scale < 1.  

This issue describes a new parameter which would change the avatar to treat scale === 1 the same as CSS background-size === contain (where the current behaviour is like cover).

**Comment by mosch** [comment]
I think that can be done by programmatically setting a different scale, so close this now.

**Comment by murilozilli** [comment]
@mosch can you give an example?
