### ISSUE TITLE
The initial image size should mimic background-image "cover" instead of "contain"

### ISSUE THREAD

**Issue by chengyin** [mosch/react-avatar-editor#15]
This is an example:
http://jsfiddle.net/chengyin/Lfdbodtr/2/

When the cropping field isn't a square, interesting things happen. In this case, the image will be contained in the viewport, instead of covering the whole viewport. Without scaling, the image can't even be moved around.

Since the desired function for this component is to crop the image to fill up a certain size, I do not think the behavior here is expected.

**Comment by chengyin** [comment]
http://jsfiddle.net/chengyin/Lpzh4r2f/1/

I modified `getInitialSize` to fix it.

**Comment by mosch** [comment]
@chengyin thanks. the second editor in your [second example](http://jsfiddle.net/chengyin/Lpzh4r2f/1/) shows an other problem. the image cant get moved to the top.
