### ISSUE TITLE
Facing CORS issue

### ISSUE THREAD

**Issue by granjan** [mosch/react-avatar-editor#156]
I tried accessing a remote image on AWS S3, but it still gives a CORS issue, even though the S3 policy is set to allow all origins. This works on Firefox but not on Chrome.

**Comment by granjan** [comment]
Apologies, this is not an issue with the react-avatar-editor component.
When I Disabled Cache from the chrome debugger, it fetched the remote image without any error. This looked to be a caching issue, adding a dummy timestamp solved the caching issue as well.

**Comment by alexander-daniel** [comment]
@granjan experiencing the same issue as you. Would you be able to elaborate on "adding a dummy timestamp"?

I'm able to load it also when I disable cache, but I can't figure out how to solve this. Thank you very much!

**Comment by Andriy-Kulak** [comment]
+1 @granjan and @alexander-daniel I have the same issue. Can someone explain in more detail how to do this with S3.

Thanks,
Andriy

**Comment by Andriy-Kulak** [comment]
Ahh I found the answer @granjan  was probably referring to adding a dummy date to the end of the url of the image. Link below:

`
newImage.src = "http://localhost/image.jpg?" + new Date().getTime();`

http://stackoverflow.com/questions/1077041/refresh-image-with-a-new-one-at-the-same-url
