### ISSUE TITLE
Rename the package name

### ISSUE THREAD

**Issue by geekorlife** [mosch/react-avatar-editor#163]
As the Class name is `AvatarEditor` and the package name is `react-avatar-editor`. 
The name of the component should be the same as the React name of the component.

**Comment by mtlewis** [comment]
Hey @geekorlife, just wondering if this is blocking you somehow?  As the component is the default export of the module, you can import it as whatever you like, so if you prefer to see something like `import ReactAvatarEditor from 'react-avatar-editor';` in your code, this should just work.

As for changing the name, I'm not one of the maintainers of this project, but my 2¢ is that skipping the "React" part of the name inside the package is a fairly well established pattern (e.g. react-router).

**Comment by dan-lee** [comment]
I agree with everything @mtlewis said.
We're not exporting in cjs format anyway, so it doesn't really matter as you can name the default exports in your imports as you like.

I am going to close this for now

**Comment by geekorlife** [comment]
It was not a blocking issue but when you import React-avatar-editor. It's see by the class name as `AvatarEditor`. 
At the beginning and like all component that I import, I try to fit the Class name of the component as the imported name. Specially because I use the Chrome React plugins who shows the class name of the component in the tree. 
In this case, I was doing like the exemple: `import ReactAvatarEditor from 'react-avatar-editor'`. But when I was looking for in the tree, I was not able to found it directly via the search bar because React saw it as `AvatarEditor`.
