### ISSUE TITLE
React 15.5.0 support

### ISSUE THREAD

**Issue by zslabs** [mosch/react-avatar-editor#165]
Hi! Was wondering if [React 15.5.0](https://facebook.github.io/react/blog/2016/04/07/react-v15.html) support was on your radar. Not that it's technically broken, but because of the separation of the `PropTypes` separation, using your package in newer projects shows a lot of warnings. Happy to work on a PR for this, but wasn't sure what else was tied up that may be targeting older versions.

**Comment by mosch** [comment]
propTypes have been fixed here: https://github.com/mosch/react-avatar-editor/pull/166
anything else that is breaking?

**Comment by zslabs** [comment]
Great! I believe that's the only thing I noticed. I guess we can just leave this open until that is merged and released (for anyone else coming to the repo for the same thing). Thanks!!!

**Comment by dan-lee** [comment]
`9.1.0` has already been released 💪. So I think we can close it :)
