### ISSUE TITLE
NPM Error: Can't resolve 'prop-types'

### ISSUE THREAD

**Issue by franzwarning** [mosch/react-avatar-editor#167]
Hey Guys -- nice work on the package. However, I'm running into an issue with the `prop-types` package... I see it was recently added as a `devDependency` in your `package.json`, but the first line of your `src/index.js` is `import PropTypes from 'prop-types'`. Wouldn't that imply that it's NOT a `devDependency` but rather a `dependency`? Am I missing something here?

In other news, great work on this package!

Cheers,
Raymond

**Comment by mosch** [comment]
@franzwarning should be fixed in 9.1.1 can you proof?
