### ISSUE TITLE
canvas.toBlob(...) doesn't work in Safari and IE

### ISSUE THREAD

**Issue by Andriy-Kulak** [mosch/react-avatar-editor#170]
I needed to store the cropped image in S3 so I converted image to blob then stored in S3 respectively. This only works in Chrome, but not Safari and IE (I forgot if it works in Firefox or not). Below is the code that was used and broke as mentioned above. I ended up doing a workaround by converting the canvas to base64 (canvas.toDataUrl( ...)) and that works in all 4 browsers.

Just want to give a heads up and curious if other people experienced a similar issue!

Error below:
`TypeError /react-text react-text: 4 : /react-text react-text: 5 canvas.toBlob is not a function. (In 'canvas.toBlob(function (blob) { _this2.props.uploadCroppedActionPhoto(blob); })', 'canvas.toBlob' is undefined)`

function Below
```
    const onClickSave = () => {
      const canvas = this.editor.getImage();
      console.log('regular canvas ', canvas);
      // returns normal canvas image

      const canvas2 = this.editor.getImage().toDataURL('image/png', 1);
      console.log('base 64 image', canvas2);
      // Works well in all browsers

      canvas.toBlob((blob) => {
        console.log('blob image', blob);
        // Errors in Safari, IE and potentially Firefox
      });
   }
```

Component Below
```
                <AvatarEditor
                  image={imgSrc + '?' + new Date().getTime()}
                  ref={this.setEditorRef}
                  width={this.props.params.size.cropWidth}
                  height={this.props.params.size.cropHeight}
                  crossOrigin="anonymous"
                  border={25}
                  color={[255, 255, 255, 0.6]} // RGBA
                  scale={1}
                  rotate={0}
                />
```

**Comment by Jinksi** [comment]
I solved this by adding this polyfill [canvas-toBlob](https://github.com/eligrey/canvas-toBlob.js)

**Comment by Andriy-Kulak** [comment]
fair enough @Jinksi !
