### ISSUE TITLE
Scaled final image

### ISSUE THREAD

**Issue by louman347** [mosch/react-avatar-editor#171]
### Feature Request:

This component seems to only crop images that preview at a 1:1 scale. It does not handle editing larger images in a smaller form factor very cleanly.

For example, if I want to crop a `1920x1080` image, but inside an avatar editor that is `177.78x100`, the image is resized to be `177.78x100` and loses most of its crisp resolution. The best workaround I've been able to muster is making the editor be `1920x1080`, then styling it to be `177.78x100`, which results in a really slow move speed because the editor behaves like it's 10.8 times its actual size. To fix the move speed, I utilized the `onPositionChange` prop function to calculate the difference between the `position` (x and y)  and the last position (tracked by a state variable), then multiplying that difference by the scale factor (in my case 10.8). Here is my solution in code:

```javascript
avatarPositionChanged(position) {
  const dragScale = 10.8  // Ratio of image size to editor size (1080/100)

  var addX = (position.x - this.state.dragPosition.x) * dragScale
  var addY = (position.y - this.state.dragPosition.y) * dragScale

  this.setState({
    ...this.state,
    dragPosition: {
      x: this.state.dragPosition.x + addX,
      y: this.state.dragPosition.y + addY
    }
  })
}

...

<AvatarEditor
  image={this.state.imageURL}
  width={1920}
  height={1080}
  border={0}
  scale={1}
  onPositionChange={this.avatarPositionChanged.bind(this)}
  position={this.state.dragPosition}
/>
```

This workaround nearly works nicely, except that the dragging motion can be a little jumpy and the editor seems to have trouble when the image has reached an edge.

---

### Proposed solution:
The props `width` and `height` should get more explicitly defined as `imageWidth` and `imageHeight`, followed by an independent `canvasWidth` and `canvasHeight` that don't resize the image. If they are not defined, `canvasWidth` and `canvasHeight` can be set to the values of `imageWidth` and `imageHeight` to maintain the 1:1 aspect ratio that the editor currently has.

**Comment by mtlewis** [comment]
Are you using `getImage` to retrieve your cropped image? IIRC, this function should give you a crop of your original image without any scaling applied. The `getImageScaledToCanvas` method scales the image according to the width and height props.

**Comment by louman347** [comment]
I have now changed my approach to use `getImage`, so thank you for pointing that out. However, while it does return the full resolution crop of the original image (which is the final result I was looking for), it does not show a full resolution preview of the image while it's being edited, just the downscaled version of it. Did I miss something else?

**Comment by hu9o** [comment]
So what you need is antialiasing or a decent scaling method (e.g. bicubic interpolation) so the image looks good in the editor?

react-avatar-editor doesn't help with this yet, but there are ways: http://stackoverflow.com/questions/17861447/html5-canvas-drawimage-how-to-apply-antialiasing (someone in here mentioned the *pica* lib)

**Comment by louman347** [comment]
@hu9o it appears so. I didn't realize this was an aliasing issue with the `canvas` element. I've had little experience with canvases, so thank you for teaching me something.

From that StackOverflow answer, it appears either the bicubic interpolation or [pica](https://github.com/nodeca/pica) seem like a good solution for what I'm looking for.

**Comment by hu9o** [comment]
You're welcome, I think you will need to fiddle with react-avatar-editor's source to find a solution.
Antialiasing could be a nice feature for the editor!
