### ISSUE TITLE
Cropped JPG Image becomes larger than original

### ISSUE THREAD

**Issue by Andriy-Kulak** [mosch/react-avatar-editor#172]
I have been using this package and its been great so far.

I did notice a problem with cropping larger images. In one case, the original JPG image is 1.1mb and the resulting cropped image is 9mb. which is crazy inefficient. I am storing the resulting image in S3 takes several seconds. The cropped images should all be less than the original images proportionally to what I crop, no? **Any idea on what can possibly be wrong?**

More before and after sizes for JPG images...
original -> cropped
1.1mb    -> 9.6mb (cropped around 80% of the original)
2.8mb   -> 16mb (cropped around 80 % of the original)
18mb     -> 17mb (cropped about 30% of the original)

Here is my component:
```
<AvatarEditor
                image={`${imgSrc}?${new Date().getTime()}`}
                ref={this.setEditorRef}
                width={this.props.params.size.cropWidth}
                height={this.props.params.size.cropHeight}
                crossOrigin="anonymous"
                border={25}
                color={[255, 255, 255, 0.6]} // RGBA
                scale={1}
                rotate={0}
              />
```

and function

```
  onClickSave() {
    const canvas = this.editor.getImage();

      canvas.toBlob((blob) => {
        console.log('blob image', blob);
        this.props.uploadCroppedActionPhoto(blob);
      });
  }
```

**Comment by mtlewis** [comment]
The canvas.toBlob method accepts quality as the third parameter - IIRC the default produces very large jpegs, regardless of the input - you might want to play with this value to try and get a size/quality compromise that works better for you.

**Comment by mosch** [comment]
Also it seems that converting from different file formats produces large files sizes. This could be something to add into the editor.

**Comment by Andriy-Kulak** [comment]
@mosch @mtlewis This seems to be happening with multiple file formats. I tried mostly jpegs and some png's and it's inconsistent. So some resulting crops are smaller than the original image (which is the expected behavior) while others are much bigger (5x or more than the original). I only crop out around 10% off from each image. I still haven't found the reason this is happening, but I may send the coordinates from react-avatar-editor and try server side cropping with [sharp npm package](https://github.com/lovell/sharp) if I can't figure out a solution soon

**Comment by oyeanuj** [comment]
@Andriy-Kulak Curious, where did you end up with this?

**Comment by ottoo** [comment]
Im seeing this behavior also with another cropping tool react-cropper, which is based on cropperjs. When I crop a JPEG and save it as PNG toBlob, the filesize seems to be consistently about 10-20% bigger.
