### ISSUE TITLE
Option to Rotate Underlying Image

### ISSUE THREAD

**Issue by zsteiner** [mosch/react-avatar-editor#175]
It would be great to have an option to rotate the underlying image, rather than canvas. Does not appear to be resolved as part of Issues #139 and #144, though they were closed. If this issue was resolved, then it doesn't appear to have made it into the 9.1.1.

<img width="684" alt="screen shot 2017-05-30 at 2 16 22 pm" src="https://cloud.githubusercontent.com/assets/4006336/26598244/a8e9a82c-4542-11e7-838e-f28324bcb14d.png">

**Comment by oyeanuj** [comment]
It does seem like the 'Rotate' option is broken on the demo page.

**Comment by mosch** [comment]
fixed in latest version
