### ISSUE TITLE
Flip image

### ISSUE THREAD

**Issue by ajwagner777** [mosch/react-avatar-editor#176]
Loving this component.  Super simple and powerful.

I have a question about how best to implement a horizontal or vertical image flip.  Right now I am passing scaleX(-1) or scaleY(-1) as a style prop to the component.  However, that is flipping the whole canvas, not the underlying image.  I'd also like to pass filters, but those are less important at this juncture.  

Issue #175 seems to be a similar issue.  Is this the accepted means of manipulating the image, or would there be a better way?

**Comment by mosch** [comment]
This is not super trivial however there is stuff out there that might help. 
There is a function that implements flipping and rotating at the same time - would be worth a try.
I would add a property called flip={bool} and apply the changes to the canvas depending on that property. Check this out:  https://stackoverflow.com/questions/3129099/how-to-flip-images-horizontally-with-html5

**Comment by alan345** [comment]
It works perfectly! Thanks

```
// flipHorizontally
        context.translate(context.canvas.width , 0)
        context.scale(-1, 1)

// flipVertically
        context.translate(0 , context.canvas.height)
        context.scale(1,- 1)

```

**Comment by GeorgiosP** [comment]
#257 Have a PR that should fix the flipping of the canvas issue for anything thats not equal width and height
