### ISSUE TITLE
Version 10.0.0 commit

### ISSUE THREAD

**Issue by h-michael** [mosch/react-avatar-editor#181]
Version 10.0.0 has already been published to npm, but commit is not at github.
Please push version 10.0.0 commit to github.

**Comment by oyeanuj** [comment]
@mosch Curious about the changes as well - is there a changelog or release notes somewhere?

**Comment by mosch** [comment]
done, @oyeanuj valid point. were do you like to see them?

**Comment by oyeanuj** [comment]
@mosch Most repos end up using Releases Tab or just starting a simple `Changlelog.md` which is updated every time someone commits (you could enforce this as part of accepting a PR as well). Here is the format that I see most using - http://keepachangelog.com/en/1.0.0/

**Comment by mosch** [comment]
@oyeanuj thanks!
