### ISSUE TITLE
PNG with transparency canvas.toDataURL('image/jpeg')

### ISSUE THREAD

**Issue by paulincai** [mosch/react-avatar-editor#182]
Hi,

I am trying to give the canvas a white background on componendDidMount() and I can see the white filling is happening. However the drawing of the dropped image seems to cancel that and after saving the image I get the default black background which is expected from a canvas.
`  const canvas =  $('canvas')[0]

    var ctx = canvas.getContext('2d')

    ctx.fillStyle = '#ffffff'

    ctx.fillRect(0, 0, canvas.width, canvas.height)

    console.log(ctx) // shows the white filling
`
I tried the same with onDropFile, onLoadSuccess, onImageReady. I don't seem to be able to fill white and draw a transparent PNG on top of that background.

onLoadSuccess, onImageReady fill white and overwrite the dropped image.

Any solution to get a colored background to a PNG with transparency, using the props of react-avatar-editor?

Thank you, Paulo

**Comment by paulincai** [comment]
For those interested, I found a way to do it after the image is being produced by this module and before uploading to cloud (Cloudinary in my case)

The solution can be found here: https://stackoverflow.com/questions/13073647/crop-canvas-export-html5-canvas-with-certain-width-and-height

I think this can be fully implemented in this module with a prop to chose the background color.
My benefit is that I save a transformation in Cloudinary which is $.

**Comment by mosch** [comment]
@paulincai I'm closing this since you figured out a solution. For the logs: You may utilize getImage() and continue working on your canvas object to do such things.

**Comment by afilp** [comment]
@paulincai See here what I did and it worked (based on your remarks, thanks!)
https://github.com/mosch/react-avatar-editor/issues/282

@mosch Would you like a PR for that, for optional BG color?
