### ISSUE TITLE
Image Positioning on Rotate

### ISSUE THREAD

**Issue by zsteiner** [mosch/react-avatar-editor#183]
Thank you for implementing image rotating (#175). I'm seeing some odd behavior in the demo, however. It looks like the canvas is rotated as well as the image. This is easy to resolve with swapping height and width on 90 degree rotate. 

The image position is not as expected. On rotate the image is outside of the canvas. Scaling and panning can get it part of the way into the crop area, but there is something preventing the image from filling the canvas. In the screenshots, the whitespace in the canvas reflects the point at which you cannot pan more. It appears to be rotating from the top left origin, which is normal in rotate. Would x and y position need to be adjusted on rotate to keep the center of the image positioned in the center canvas?

<img width="666" alt="screen shot 2017-07-13 at 8 36 22 am" src="https://user-images.githubusercontent.com/4006336/28166670-d08add16-67a6-11e7-83fc-ca4b7b68f42e.png">

<img width="709" alt="screen shot 2017-07-13 at 8 40 35 am" src="https://user-images.githubusercontent.com/4006336/28166701-f7728a8c-67a6-11e7-9798-6e8b9cd9348e.png">

**Comment by oyeanuj** [comment]
Also running into this even though [this comment](https://github.com/mosch/react-avatar-editor/issues/175#issuecomment-314996157) says it is fixed.

**Comment by mtlewis** [comment]
This certainly *was* working when I first implemented the position prop - something must have borked it. Will take a look.

**Comment by mtlewis** [comment]
Looks like this is a regression introduced with https://github.com/mosch/react-avatar-editor/pull/121.  Will see if I can get a fix ready.

**Comment by mtlewis** [comment]
Found the problem - see #188.

**Comment by mosch** [comment]
@zsteiner released new version. can you verify it's solved?

**Comment by zsteiner** [comment]
It's working well in the demo. Thank you!

**Comment by zsteiner** [comment]
Got it integrated to our app and works fantasticly. Just had to swap canvas height/width on 90 degree turns. Greatly appreciate the work, everyone who pitched in.
