### ISSUE TITLE
Show grid guides on the image

### ISSUE THREAD

**Issue by oyeanuj** [mosch/react-avatar-editor#185]
Hi @mosch, while researching for this library, I saw some other libraries providing a grid guide on the image. This would be super useful for users to have when moving their image - to follow the rule of thirds, for example.

Just wanted to put it out there, so that it is on your radar.

**Comment by mosch** [comment]
Hey @oyeanuj, thanks for pointing this out. Without snapping it would be easy to implement i guess.

**Comment by oyeanuj** [comment]
@mosch thanks! what does 'snapping' refer to in this case?

**Comment by mosch** [comment]
I thought about snapping to the grid. But - that was a bit offtopic.

**Comment by oyeanuj** [comment]
Ah, got it. I agree though - just a simple grid might be a sweet v1 for it!
