### ISSUE TITLE
Access to canvas's ImageData

### ISSUE THREAD

**Issue by oyeanuj** [mosch/react-avatar-editor#186]
Hi @mosch or anyone around, I am not super familiar with `canvas`, so hence a question/request. I am trying to use [this library](https://github.com/canastro/image-filter-sepia) for image filters. This requires `imageData` as a parameter which seems to be derived from the canvas.

So, since `react-avatar-editor` is already dealing with a canvas for this image,  I am wondering if it is possible today (or possible to expose) the `getImageData` from the canvas, so that information can be used for such purposes?

Thanks!

**Comment by mtlewis** [comment]
The component has a `getImage` method which returns a canvas with the image drawn on it. Should be what you need! :+1:

**Comment by oyeanuj** [comment]
@mtlewis Thanks for the response! It seems like the problem there is that to get the `imageData` from a canvas' context, one has to provide dimensions of the image on the canvas for which you need the image data. That's something that only the editor has access to..

So, I guess my clarified need is to have a method similar to `getImage` and `getImageScaled` which provide `imageData` like `getImageData` or `getImageDataScaled`, or to get the positions used in those methods be publicly accessible or returned through the `getImage` methods as well.

I don't understand the positioning logic enough to make the PR myself, so any thoughts?

_(edited comment above to reflect the same)_

**Comment by mtlewis** [comment]
Have you tried using [`canvas.toDataURL`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL) to access the image data?

**Comment by oyeanuj** [comment]
@mtlewis Not sure I follow but are you suggesting converting from `dataURI` to `imageData`? It seems like there is no direct way but I could go possibly go from `dataURI` to 'Blob` to `imageData` (the last using https://github.com/nawatts/read-image-data).

Is that what you were suggesting/recommending?

**Comment by mtlewis** [comment]
Actually if access to a Blob is what you're after, there's also [`canvas.toBlob`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob).  Does that help?  If not, maybe you could describe some details of your use case, as I feel like I'm kinda just throwing random MDN links at you in the hope one of them is what you're after right now. 😆

**Comment by oyeanuj** [comment]
Ah, that might just work! Sorry for the lack of information - I am trying to implement image filters using this library [image-filters](https://github.com/canastro/image-filters). So, I had two challenges there - one is access to `imageData` and feeding it back to `AvatarEditor`. The second is to make sure all of this conversion and manipulation is performant as one pans or moves the image in the editor. 

So far, I was stuck at the first problem. For the second problem, I am intending to get the canvas image on `onMouseMove` and translate it maybe.

Easier way to understand all that text is [this UX](https://www.mozmorris.com/react-webcam/examples/) except replace the webcam feed with the AvatarEditor, and convert image than use CSS filters.

**Comment by mtlewis** [comment]
Seems like one way to keep that performant would filtering and cropping separate - can you not just apply the image filter to the uncropped image before passing it to the avatar editor? I suspect applying an image filter to the new cropped image every time the cropping rect is changed is unavoidably going to be janky.

**Comment by mtlewis** [comment]
Hey @oyeanuj, did the suggestions above solve the problem you were running into? Just wondering if this one can be closed :)

**Comment by oyeanuj** [comment]
@mtlewis Yes, I think I am going to change strategy and convert `toBlob` and try to work with that. If in the future, someone needs `canvas`, then we could revisit. Thanks for all of your help!

**Comment by mtlewis** [comment]
Totally welcome, good luck with your filtering / cropping widget. Post a link here when it's done!
