### ISSUE TITLE
`disableDrop` Parameter Has No Effect

### ISSUE THREAD

**Issue by alexblickenstaff** [mosch/react-avatar-editor#194]
I've set `disableDrop={true}` in the `AvatarEditor`, but am still able to drag images onto it. Setting this to true seems to have no effect.

looking at the commits, it appears that this feature was only added recently? Might the build I'm using be too old (though I did an `npm install` for it today)? My version is `^10.1.0`.

**Comment by mtlewis** [comment]
Yep, looks like `disableDrop` is merged to master buy is not part of the latest release. @mosch, should we do another release to get this feature out?

**Comment by mosch** [comment]
Released https://github.com/mosch/react-avatar-editor/releases/tag/v10.2.0

**Comment by alexblickenstaff** [comment]
Sorry if there's a better way to find this information out (I'm new to the js ecosystem). Is there something you have to do for it to appear as a release [here](https://www.npmjs.com/package/react-avatar-editor)? The latest release there is `10.1.0` not `10.2.0`. Is there another way to access the latest release via a `package.json` file?
