### ISSUE TITLE
Image quality flag?

### ISSUE THREAD

**Issue by MovingGifts** [mosch/react-avatar-editor#198]
In my save method I have this:

```js
const canvasScaledUrl = this.refs.editor.getImageScaledToCanvas().toDataURL();
```

The image doesn't look like the best quality though. I am not sure how to control the quality level of the image above. Can someone please jump in with how to do it?

**Comment by dan-lee** [comment]
[`toDataUrl()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL#Parameters) has a second parameter for the quality. Default is 0.92, try setting it to 1. Can you check that?

```
this.refs.editor.getImageScaledToCanvas().toDataURL('image/jpeg', 1)
```

**Comment by MovingGifts** [comment]
Works great, thank you!
