### ISSUE TITLE
Add "disabled" property to disable dragging

### ISSUE THREAD

**Issue by alexblickenstaff** [mosch/react-avatar-editor#199]
Is it possible to disable the dragging of this component? It'd be nice to be able to have a way to toggle user interactivity with the component (i.e. a `disabled` prop) programatically

**Comment by mosch** [comment]
hey @alexblickenstaff. thanks for bringing this up. could you be more specific about dragging? do you mean drag n drop upload or dragging the image position?

**Comment by alexblickenstaff** [comment]
I mean everything actually -- the idea would be that when the component is "disabled", a user can no longer interact with. Dragging another image onto it would do nothing, dragging the image would do nothing, etc. I think it'd be nice to have this when a user is "done" editing so that the current crop location can be locked where it is

**Comment by mosch** [comment]
ok got it, just the same behaviour like an HTML input field would give you. i like this 👌🏼
