### ISSUE TITLE
No file chosen error even after uploading file

### ISSUE THREAD

**Issue by decentname** [mosch/react-avatar-editor#201]
![screen shot 2017-09-27 at 12 41 46 pm](https://user-images.githubusercontent.com/12930790/30900282-0d000080-a381-11e7-800d-b658f246b239.png)

Even after uploading file, i get a flash saying no file chosen. Why is this happening?

**Comment by dan-lee** [comment]
Could you provide a demo or a [Code Sandbox](https://codesandbox.io/s/new) to reproduce this issue?

**Comment by decentname** [comment]
Sure. Try here:
 [https://codesandbox.io/s/2wzn26nz4r](url)

**Comment by mosch** [comment]
This works for us, so I'm closing this. It looks to me that this is a Tooltip. I don't know where its coming from, I think it's not related to this component.
