### ISSUE TITLE
Add React 16.0 support/dependency version.

### ISSUE THREAD

**Issue by bytor99999** [mosch/react-avatar-editor#202]
Was hoping you might be able to get a release out that has React 16.0 version as a dependency.

Love the component, been using it for a while on a 0.13 React app that we are just now getting to try and upgrade to the latest React version.

Thanks

Mark

**Comment by mosch** [comment]
Hey there, supported in version 10.3.0 https://github.com/mosch/react-avatar-editor/releases/tag/v10.3.0
