### ISSUE TITLE
Fix dragging behaviour of images smaller than viewport

### ISSUE THREAD

**Issue by aleemb** [mosch/react-avatar-editor#204]
Would you consider exposing `disableDrag={true}`?

In the circumstance that an image is smaller than the cropper viewport, it makes sense to disallow dragging of the image. I have a use case to allow small images, that don't need cropping. This deviates from the current default behaviour of stretching small images to fit the viewport which can be limiting.

Thanks for you consideration.

**Comment by aleemb** [comment]
On second thought, the dragging behaviour of tall+narrow images, small images and wide+short images needs to be bounded correctly.

Tall images with zoom < 1 should be draggable vertically only. Wide+short with zoom < 1 images should be draggable horizontally only. And images smaller than the viewport (again, zoom < 1) don't need to be draggable at all.

**Comment by mosch** [comment]
Disable dragging is disussed here: https://github.com/mosch/react-avatar-editor/issues/199

However there seems to be a bug for images smaller than the viewport. I agree they should not be draggable at all at initial scale.

**Comment by mosch** [comment]
Still not entirely sure what your request is! Feel free to respond, I'll reopen then.

**Comment by aleemb** [comment]
The issue the following bug as you acknowledged,

> However there seems to be a bug for images smaller than the viewport. I agree they should not be draggable at all at initial scale.

To work around it, I was proposing some way to disable dragging for the image position (not the upload file drag-n-drop).
