### ISSUE TITLE
Provide TypeScript definitions

### ISSUE THREAD

**Issue by huangsav** [mosch/react-avatar-editor#205]
This's a good component, hope to use it in typescript, but now I can only add the d.ts file by myself.

**Comment by mosch** [comment]
PR on typescript welcome!

**Comment by huangsav** [comment]
@mosch I add the d.ts file, but seems it has some bugs. There is no toolbar while the component show.




![k040_ d f 7f8pnrl1a a](https://user-images.githubusercontent.com/15684776/32031835-21bf478a-ba36-11e7-9285-4e6380f11d29.png)

**Comment by mosch** [comment]
@huangsav you need to build the toolbar by yourself. It's not included in the component.

**Comment by andelizondo** [comment]
I'm using this typings with no problems, so maybe they work also for you? 

`declare module "react-avatar-editor" {

    import * as React from "react";

    interface ImageState {
        height: number;
        width: number;
        x: number;
        y: number;
        resource: ImageData;
    }

    interface AvatarEditorProps {
        image: string | File;
        width?: number;
        height?: number;
        border?: number;
        borderRadius?: number;
        color?: number[];
        style?: Object;
        scale?: number;
        onDropFile?(event: DragEvent): void;
        onLoadFailure?(event: Event): void;
        onLoadSuccess?(imgInfo: ImageState): void;
        onMouseUp?(): void;
        onMouseMove?(): void;
        onImageChange?(): void;
    }

    export interface AvatarEditorClass {
        getImage(): HTMLCanvasElement;
    }

    const AvatarEditor: React.ClassicComponentClass<AvatarEditorProps>;
    export default AvatarEditor;
}
`

**Comment by diogocorrea** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24138

**Comment by mosch** [comment]
Yay! Thank you!
