### ISSUE TITLE
Scaling reference?

### ISSUE THREAD

**Issue by jeanpaulpollue** [mosch/react-avatar-editor#206]
I am not sure it is much intuitive to base the image scaling upon the canvas size.
I would rather have based this value on the original image size instead.

Not sure if I made myself clear about this.
But for instance, if the provided scale value is set to 1, I should have my imported image size at it's original size.
If the value is set to 2, I should have it upscaled twice the original size.

This way you would make it much easier to integrate for people who don't want any upscaled image, for image quality's sake.

That said, I would gladly contribute to the change :)

**Comment by mosch** [comment]
I think both are valid use cases. However if you base the scale on the original image, you have no idea how "small / big" it really is. 
What this component tries to do is creating images that are the same size. 
For your use case however, i think it a simple calculation that can be done outside of the component. And you could just limit the "scale" by your self.
