### ISSUE TITLE
Example code does not work

### ISSUE THREAD

**Issue by spoco2** [mosch/react-avatar-editor#207]
Example code from the README: 
```
import React from 'react'
import AvatarEditor from 'react-avatar-editor'
...
```

Does not work, at least not in current versions of React/Typescript/Webpack. The built version of react-avatar-editor does not export the correct format for this command to work.

Replacing with :  
```
import * as React from "react";
const AvatarEditor = require("react-avatar-editor");
```

Makes the code work as expected

**Comment by mosch** [comment]
Thanks, but that's only if you use Typescript. I like to keep it how it is for all "normal javascript" (if there is anything like that)
