### ISSUE TITLE
Index.js line 210 - is getImage() used?

### ISSUE THREAD

**Issue by paulincai** [mosch/react-avatar-editor#208]
Hi there,

I am looking into index.js. At line 210 you start a function getImage(). It looks that this function is of no particular use. Is that right?

Then at line 270 you have :
`/**
   * Get the image scaled to original canvas size.
   * This was default in 4.x and is now kept as a legacy method.
   */
  getImageScaledToCanvas () {....`

I suppose the legacy method is still the one in use.

Great work!

Thank you,
Paul

**Comment by mosch** [comment]
We use it by ref to get access to the image.
