### ISSUE TITLE
Maintain Cropping Rectangle orientation upon image rotation

### ISSUE THREAD

**Issue by FredGauld** [mosch/react-avatar-editor#210]
Hi, 
Thanks for the great component.  

I'm trying to let the user rotate image within the cropping rectangle.  

Right now, the cropping rectangle rotates with the image, which prevents the user from actually rotating the image within the frame. 

Any ideas on a workaround?

Thanks!

**Comment by mosch** [comment]
Hey @FredGauld,
I think thats a quite unintuitive behaviour, however since we are only using squared cropping rectangles we don't have any issues with this. I don't have any workaround ready for this right now. But we should change that.

**Comment by FredGauld** [comment]
Hi @mosch, 
Actually, I "moved the thought, not the rock".  ...I found a very simple workaround:   to go with square cropping for my webapp  :-)  
Thanks!

**Comment by mosch** [comment]
Thanks. So I close this for now. But I still think we should tackle this at some point.

**Comment by sun2rise** [comment]
any news? i still have this problem
