### ISSUE TITLE
Something in between getImage() and getImageScaledToCanvas()

### ISSUE THREAD

**Issue by nareshbhatia** [mosch/react-avatar-editor#213]
`getImage()` grabs the image at full resolution, which means that the captured image can be very large. `getImageScaledToCanvas()` on the other hand allows us to control the size of the captured image to the size of the canvas. However neither option is working well for me. I set the canvas to 320x320. The captured image is not of good enough quality. I can't put up larger canvases, e.g. 1024 x 1024 - these are just not practical from a UX perspective. Is there a better way? For  example, is there a way to specify the size of the captured image independent of the canvas size?

Thanks in advance.

**Comment by mosch** [comment]
You should go for getImage() and resize it yourself

**Comment by nareshbhatia** [comment]
Thanks for the quick response, @mosch. I haven't played with images enough so don't know how to do this. Could you please point me in the right direction?

**Comment by mosch** [comment]
@nareshbhatia getImage() returns a canvas object for you that you can work with. Check out [this SO article](https://stackoverflow.com/questions/19262141/resize-image-with-javascript-canvas-smoothly) to see how image resizing is done in canvas.

**Comment by nareshbhatia** [comment]
Thanks, @mosch. I am trying it out.
