### ISSUE TITLE
Publisher in npm repositories

### ISSUE THREAD

**Issue by nicolascbarbosa** [mosch/react-avatar-editor#216]
Add this repo in npm repositories, i would like to add it as dependency in my project.

**Comment by mosch** [comment]
Its available on NPM as https://www.npmjs.com/package/react-avatar-editor
Is there anything we are missing?

**Comment by nicolascbarbosa** [comment]
Firstly 🥇 , thanks for your answer. After in my first search in README.md file and npmjs.com repo's, i am not found, It must be because i was sleepy 😕

**Comment by dan-lee** [comment]
@nicolascbarbosa I just added some instructions in the README after I saw your issue. Thanks for your input.

**Comment by mosch** [comment]
Thanks to everyone! 👍
