### ISSUE TITLE
Possible to set required image dimensions?

### ISSUE THREAD

**Issue by bhellman1** [mosch/react-avatar-editor#217]
Is it possible to set a required width & height for upload images? For example, when uploading a small profile photo to facebook, the facebook web UI will alert "Please choose a photo that's at least 180 pixels wide." Can react-avatar-editor support this ability?

**Comment by mosch** [comment]
Hey @bhellman1 - thanks for bringing this up! We want to keep this component lightweight and small and we don't want to add this feature into the avatar editor. 

Butyou can add easily add this by listening to the onDropFile callback, than measure the file and display a message if necessary.
