### ISSUE TITLE
picture muzzy

### ISSUE THREAD

**Issue by yangfan0095** [mosch/react-avatar-editor#219]
this is the code to get image :

` const img = this.editor.getImage().toDataURL('image/png', 1);`

and my  screen is MacBook Pro  。 when i transformed , the image being muzzy.
anyway can handle this ?

![image](https://user-images.githubusercontent.com/21197847/35131334-85ea036e-fd00-11e7-90a5-2e43cd8b1d6b.png)

**Comment by yangfan0095** [comment]
i had saw some way on internet , such add the drawImage size for width and height ,but it never work  ,still muzzy  。 and  i had used the npm package 'hidpi-canvas-polyfill' ,just like  it's not compatible with avator  。

**Comment by yangfan0095** [comment]
I had  handle this by increasing the  canvas image size   , but I think it's not a good way to solute it .
maybe there is a way  is that  we can get a canvas by  the callback  'getImae() ' . and re render a image by current state ( scale , position , ), but also   complex 。 
 my english is poor   , and I am a Chinese 😆.

**Comment by mosch** [comment]
Hey @yangfan0095, could you fix this problem?

**Comment by yangfan0095** [comment]
@mosch  it seem has no good way to fix it , quality  loss seem to be inevitable,   just can handle it by some hack way , like use the npm package 'hidpi-canvas-polyfill ' , like increasing canvas size   , and Avator provide  a useful API  getImage()  that we can get the canvas  Object and deal it by own way ,I think it is the best way to do that 🤔

**Comment by yangfan0095** [comment]
and one anther issue is  https://github.com/mosch/react-avatar-editor/issues/220  ,I can't understand   the  code ` return this.props.rotate % 180 !== 0` ,why you judge vertical by %180🙄

**Comment by martisj** [comment]
Did you ever figure out a fix for this @yangfan0095 ? We are getting the same issue and I saw from the source code that the suggested fix to scale the Canvas 2x shows the canvas nicely, `editor.getImageScaledToCanvas()` still returns an image with the perceived width and height of the image. Any help is muy apreciado 🙏
