### ISSUE TITLE
Images in Base64 don't work in Firefox

### ISSUE THREAD

**Issue by adrianes** [mosch/react-avatar-editor#22]
If you use a Base64 image the component don't work in Firefox, its maybe because of the way you handle the loading of the image.

You can find some reference in [here](http://stackoverflow.com/questions/23075778/firefox-image-base64-data-using-canvas-object-not-working)

**Comment by codedmart** [comment]
@adrianes I submitted a pr that fixes the problem. It was merged but a new release has not happened yet.

**Comment by adrianes** [comment]
Thank you @codedmart have a great day
