### ISSUE TITLE
reset size by  this.isVertical() ，it does not compatible width canvas that width not equal height

### ISSUE THREAD

**Issue by yangfan0095** [mosch/react-avatar-editor#220]
Summary ： **when the react render  ,the getDimensions() will be call , and you will reset the size according to the function  this.isVertical(). and the key is  the function   ` this.isVertical() `  that 
you  judge if it is vertical by `  this.props.rotate % 180 !== 0 `  。 if you judge by this , it will not compatible width canvas that width not equal height. just like my project .**

if the canvas  width not equal height , when rotate will be canvas  will be reset 。 just like the picture

![image](https://user-images.githubusercontent.com/21197847/35206811-336d1cd0-ff7a-11e7-942c-2f1836f5c81c.png)

when  rotate , it will be deform ,it just seem  not support rectangle

![image](https://user-images.githubusercontent.com/21197847/35207084-f52d61d0-ff7b-11e7-8d1e-5274d60c28e2.png)

i saw your code .
when the react render  ,the getDimensions() will be call , and you will reset the size according to the this.isVertical(). and the key is  the function   ` this.isVertical() ` 
you  judge if it is vertical by `  this.props.rotate % 180 !== 0 `  。 if you judge by this , it will not compatible width canvas that width not equal height. just like my project .

```
 render () {
    const dimensions = this.getDimensions()
...
```

```
  getDimensions () {
    const { width, height, rotate, border } = this.props

    const canvas = {}

    const [borderX, borderY] = this.getBorders(border)

    const canvasWidth = width
    const canvasHeight = height

//  here is the judge way
    if (this.isVertical()) {
      canvas.width = canvasHeight
      canvas.height = canvasWidth
    } else {
      canvas.width = canvasWidth
      canvas.height = canvasHeight
    }

    canvas.width += borderX * 2
    canvas.height += borderY * 2

    return {
      canvas,
      rotate,
      width,
      height,
      border
    }
  }
```
and the isVertical 

```
isVertical () {
    return this.props.rotate % 180 !== 0
  }

``` 

such as my  project ：

![image](https://user-images.githubusercontent.com/21197847/35207003-7ebccea0-ff7b-11e7-8d91-190c6a130925.png)

**Comment by yangfan0095** [comment]
```
  isVertical () {
    return this.props.rotate % 180 !== 0
  }

```

**Comment by yangfan0095** [comment]
i fix my problem by change your  original code .  and I think maybe you can provide a API  to controller that 🙂
```
isVertical () {
   -  return this.props.rotate % 180 !== 0;
   + return false;
  }
```

**Comment by GeorgiosP** [comment]
Is this a PR'd fix or should I also modify it?
