### ISSUE TITLE
applying a filter to the image

### ISSUE THREAD

**Issue by kent10ou** [mosch/react-avatar-editor#221]
Is there currently a way to apply a filter to the image? such as sepia, greyscale, brightness, contrast, etc.? The `color` prop seems to only work on the border or cropped out area. Thanks!

**Comment by oyeanuj** [comment]
@kent10ou Similar usecase. It seems like the best way to do it right now would be to apply the custom CSS to the canvas.

@mosch Any other suggestions?

**Comment by oyeanuj** [comment]
@mosch That API looks great. Would this essentially affect the CSS of the canvas? 

Also, if we do go ahead in this direction, it would be super useful to have the `getImage...` API return both filtered or non-filtered canvas depending on the param.

**Comment by mosch** [comment]
@oyeanuj i'm planning to write some demos using something like https://github.com/zhengsk/ImageFilters.js

**Comment by kent10ou** [comment]
Awesome! Thanks @oyeanuj and @mosch! I'll give the above suggestion a shot

**Comment by oyeanuj** [comment]
@kent10ou Let us know if you are able to build something before @mosch - curious to see what works best.
