### ISSUE TITLE
onImageChange shouldn't fire image property change

### ISSUE THREAD

**Issue by mschipperheyn** [mosch/react-avatar-editor#223]
I auto save my image x seconds after it changed.
However, it then uploads and the url changes. Because the editor fires an image change event when the props.image changes, I end up with an endless cycle. the imageChange event should imho only fire when the image is edited, not when the props.image changes.

**Comment by mosch** [comment]
Good catch, happy to accept a PR for this one. Even if it will be breaking ...

**Comment by oyeanuj** [comment]
@mschipperheyn I landed in the same problem, curious what your solution was? Tapping into other callbacks other than `onImageChange`?

**Comment by mosch** [comment]
@oyeanuj @mschipperheyn check out latest release, it should fix this.
