### ISSUE TITLE
Return Type of getImage

### ISSUE THREAD

**Issue by jyash97** [mosch/react-avatar-editor#226]
Instead of returning _Canvas_ from `getImage` can we return a `blob URL` which can be directly accessible to user like :

```js
<img src={this.getImage()} />
```
If this seems helpful I can try and give a PR.
Thanks !

**Comment by mosch** [comment]
Hey @jyash97 , thanks for your input! Some users of this library like to use the _Canvas_ from getImage() to apply some more manipulations to it. 
And you still can also call .toBlob on the canvas - so I think both is supported well right now!

**Comment by jyash97** [comment]
@mosch Yes I have converted it to blob , just thought if it can be a good addition.
Thanks for the response.

**Comment by mosch** [comment]
It's be a breaking change, and all users of this lib would need to adapt it. And that a lot of effort for a little change ;-)

**Comment by jyash97** [comment]
True that 👍
Maybe if someone raises issue again we can just add steps to convert the canvas to image to docs. In that case we won't need to change the code.
