### ISSUE TITLE
Resized image inside canvas not clear

### ISSUE THREAD

**Issue by borm** [mosch/react-avatar-editor#239]
Hi, nice library but we have problems with image quality

* https://codepen.io/greypants/pen/bmyKo/?editors=1010
* https://stackoverflow.com/questions/19262141/resize-image-with-javascript-canvas-smoothly/19262385#answer-19262385
* https://stackoverflow.com/questions/18922880/html5-canvas-resize-downscale-image-high-quality

Please use one of technics for scale image in canvas

**Comment by mosch** [comment]
Hey @borm , thanks for the links. I agree, we should implement one of these!

**Comment by mosch** [comment]
I'm closing this in fav of the [existing issue](https://github.com/mosch/react-avatar-editor/issues/200) but your links might come in handy!
