### ISSUE TITLE
Rotate image without rotate editor

### ISSUE THREAD

**Issue by Dictory** [mosch/react-avatar-editor#242]
Hello. How i can rotate only image inside editor?
except change editor\`s width/height
Thanks for answer.

**Comment by giuliogallerini** [comment]
You don't have to change the editor width and height to rotate the image in it. You have to use the property `rotate` of `AvatarEditor` to rotate the image rendered in the canvas. The rotate prop takes the degree to which the image will have to be rotated.

> e.g.

```js
<AvatarEditor
  image="https://example.com/image.jpg"
  rotate={90}
/>
```

done!

**Comment by Dictory** [comment]
@giuliogallerini thanks for answer. One small thing: `rotate` change image orientation too =(

**Comment by giuliogallerini** [comment]
@Dictory I think that's just normal behaviour when rotating a landscape image of `90deg`. It would be an error if the orientation would still be landscape right?

**Comment by Dictory** [comment]
@giuliogallerini It is normal behaviour in some cases. But we have situation when we need to rotate image with locked dimensions.
![preview](https://i.imgur.com/wPNv9Fg.gif)

**Comment by giuliogallerini** [comment]
@Dictory I think that at that point you will have to handle the width and height change your self by monitoring the rotating event. Once the the image is rotated of Xdeg you will have to change the scale of it based on the original ratio of the image.

**Comment by Dictory** [comment]
@giuliogallerini And now i do that. I think may be exist another way.

**Comment by mosch** [comment]
Closed since there is a workaround.
