### ISSUE TITLE
Upload and edit image

### ISSUE THREAD

**Issue by Eddyy** [mosch/react-avatar-editor#246]
Please I'm new to react and I have a project with a pressing deadline. I want to use the react-avatar-editor to upload an image, rotate, zoom, crop, increase height and width , brighten and preview the image, and reset everything back. How can I go about this.  I started by this but nothing shows. 

import React from 'react'
import AvatarEditor from 'react-avatar-editor'

class MyEditor extends React.Component {
  render() {
    return (
      <AvatarEditor
        image="http://example.com/initialimage.jpg"
        width={250}
        height={250}
        border={50}
        color={[255, 255, 255, 0.6]} // RGBA
        scale={1.2}
        rotate={0}
      />
    )
  }
}

export default MyEditor

**Comment by mosch** [comment]
This is very basic react help. Consider doing some react getting started or react for beginners tutorials to solve this. 👍🏻
