### ISSUE TITLE
setState({image: null}) doesn't remove the image

### ISSUE THREAD

**Issue by augnustin** [mosch/react-avatar-editor#249]
I have:

```
<AvatarEditor width={250} height={250} scale={this.state.zoom} border={50} borderRadius={250} color={[255, 255, 255, 0.6]} image={this.state.image} />
```

And a `button`, which does `this.setState({image: null})` on click. 

The state is updated, but the canvas isn't redrawn and the picture remains in the background.

I guess this is not expected, is it?

**Comment by chcamiloam** [comment]
your code should work correctly, but you can try with `this.setState({ image: "" })`, any case please check your onClick.

```javascript
handleImage(){ 
    this.setState({ image: null });
}
render(){
    return(
      <AvatarEditor width={250} height={250} scale={this.state.zoom} border={50} borderRadius={250} color={[255, 255, 255, 0.6]} image={this.state.image} />
      <button type="button" onClick={this.handleImage}>Clear Image</button>
    )
}

**Comment by psenderos** [comment]
Same issue here.
I've tried to `setState({image: null})` and `setState({image: ""})` and simply doens't work.
I've tried to workaround setting a default image, but It's not actually possible to disable the dragging of the image.

**Comment by mosch** [comment]
Can someone please come up with an demo on http://codesandbox.io? 
Will reopen if s.o. likes to do so.

**Comment by ArturasMi** [comment]
Hi, I had a same issue with removing image. I found a solution that worked fine for me, instead of setting it to blank string or null I ended up setting as array with empty string this.setState({image: [""]});
