### ISSUE TITLE
Double scroll in mobile

### ISSUE THREAD

**Issue by ShintaroNippon** [mosch/react-avatar-editor#258]
Please can one help me on this ?

I have a double scroll in mobile, how i stop scroll on image ?

![ezgif com-crop](https://user-images.githubusercontent.com/3842860/41719438-ebefea6e-7557-11e8-865c-428ebb1d6167.gif)

Iphone SE

Thanks in advance
Carlos Vieira

**Comment by karltaylor** [comment]
https://stackoverflow.com/questions/7768269/ipad-safari-disable-scrolling-and-bounce-effect

**Comment by mosch** [comment]
Should be fixed by #267
