### ISSUE TITLE
[Feature Request] InnerBorder

### ISSUE THREAD

**Issue by evangow** [mosch/react-avatar-editor#259]
Issue: The border can be difficult to see on images. If the border is dark/grey, it's difficult to see on dark images, and if the border is lighter/whiter, it's difficult to see on lighter/whiter images.

Suggested feature: expose an innerBorder prop on the `<AvatarEditor />` component, which allows you to define a border (color, width, etc.) that is around the cropping rectangle.

How does this solve this problem? You can create color contrast between the innerBorder color and the border color so that it doesn't matter whether the border color contrasts with the actual image being cropped.

Example from LinkedIn's image cropper.
<img width="743" alt="screen shot 2018-06-22 at 10 11 04 am" src="https://user-images.githubusercontent.com/2602962/41785153-4ccd5312-7607-11e8-8a5c-e6138b29800d.png">

**Comment by mosch** [comment]
Thanks for this input. Im closing this until s.o. comes up with a PR.
