### ISSUE TITLE
getImageScaledToCanvas() image size reduces

### ISSUE THREAD

**Issue by amehro** [mosch/react-avatar-editor#260]
Why using getImageScaledToCanvas() the size of the image reduces. Eg if I upload a 5 mb image and try to zoom in or zoom out or rotate the image size reduces at the end in KB's.
Even when I try to load the image and pass the blob object in createObjectURL. I see the blob object as much reduced size as compared to the size of the original image.

const load = (img) => {
            img.toBlob((blob) => {
                const image = URL.createObjectURL(blob)
  }}

**Comment by martisj** [comment]
What is the expected behaviour @amehro ?
