### ISSUE TITLE
Improve image quality output

### ISSUE THREAD

**Issue by BlakeGuilloud** [mosch/react-avatar-editor#261]
First off- thanks for the hard work that goes into maintaining this awesome project! It is super easy to use.

I am having some issues with image quality when loading file data into the editor. Here is a screen shot using the Demo project included in the codebase:
![image](https://user-images.githubusercontent.com/14660993/42193591-437f1a0a-7e3d-11e8-8552-2f89e71b8a1c.png)

The first image is hardcoded to a URL while the second has been uploaded via the provided form. As you can see, there is a loss of quality between the two images.

My apologies if this is a reported issue, I could not find it. Thanks!

**Comment by martisj** [comment]
Can you share your code @BlakeGuilloud ?
