### ISSUE TITLE
Add support support for IE11

### ISSUE THREAD

**Issue by chjiyun** [mosch/react-avatar-editor#264]
Am I the only one who discovered this problem?

**Comment by mosch** [comment]
Support for IE11 welcome!

**Comment by flyingace** [comment]
Is the problem with support for IE11 related to the lack of support for `classProperties`? I am running into this same problem in a react app I am building using `create-react-app` which doesn't support this feature yet in 3rd-party components (though it is, perhaps oddly, supported in the `cra` application code).

So I imagine that for the time being the solution might be to convert the use of `classProperties` like `static propTypes = ...` back to the convention of declaring them outside the component definition as in the example found [here](https://reactjs.org/docs/typechecking-with-proptypes.html):
```
import PropTypes from 'prop-types';

class Greeting extends React.Component {
  render() {
    return (
      <h1>Hello, {this.props.name}</h1>
    );
  }
}

Greeting.propTypes = {
  name: PropTypes.string
};
```

I'm going to look into forking your repo and making this change to see if I can get it to work for my `cra` app. If there are other things I should be looking out for I hope you'll reach out and tell me.

**Comment by lusa** [comment]
@flyingace did your fork get this working for IE11?

**Comment by lusa** [comment]
Update: @flyingace's fork does not fix the issue for me. 
CC @mosch I was able to fix this for IE11 & Edge by simply removing the check for `instance of File`- this was returning false for our app, so the Avatar Editor simply does nothing in the `loadImage` function. By removing the check for File altogether, and just checking for a String, this suddenly works for IE11 and Edge. 
`  loadImage(image) {
    if (typeof image === 'string') {
      loadImageURL(image, this.props.crossOrigin)
        .then(this.handleImageReady)
        .catch(this.props.onLoadFailure);
    } else {
      loadImageFile(image)
        .then(this.handleImageReady)
        .catch(this.props.onLoadFailure);
    }
  }`

**Comment by waiid9707** [comment]
Want a default
