### ISSUE TITLE
Web-version not working locally.

### ISSUE THREAD

**Issue by username1565** [mosch/react-avatar-editor#266]
You can add bundle.js from this source https://react-avatar-editor.netlify.com/bundle.js
to the folder "/docs" to fix this trouble and update your zip repositary on the site https://react-avatar-editor.netlify.com/

**Comment by mosch** [comment]
What do you mean by it's not working locally?

**Comment by username1565** [comment]
That means if zip downloaded, and index.html opened in browser - this not working without Internet connection.
