### ISSUE TITLE
Dependencies issue

### ISSUE THREAD

**Issue by benjamindulau** [mosch/react-avatar-editor#27]
Hey,

I'm not sure why, but when trying to install the package, I get the following dependencies error:

```bash
[vagrant@vagrant-centos65 js]$ npm install --save-dev react-avatar-editor
npm http GET https://registry.npmjs.org/react-avatar-editor
npm http 304 https://registry.npmjs.org/react-avatar-editor
npm ERR! peerinvalid The package react does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-avatar-editor@0.4.9 wants react@^0.12
npm ERR! peerinvalid Peer react-modal@0.1.1 wants react@>=0.12.0
npm ERR! peerinvalid Peer react-dnd@0.9.8 wants react@>=0.12.0 <0.14.0
npm ERR! peerinvalid Peer fluxible@0.3.1 wants react@0.13.x
```

I have react@0.13.1 installed, so it shouldn't complain because you specified `react: ^0.12` as a dependency. I'm not sure what to do here, is there a way to fix this properly?

Note that without react-avatar-editor, everything is installing fine.

Thanks

**Comment by mosch** [comment]
i removed the peerDependencies, can u test this?

**Comment by benjamindulau** [comment]
Seems good.
Thanks ;-)

**Comment by mosch** [comment]
great!
