### ISSUE TITLE
getImage() and getImageScaledToCanvas() always returns default coordinates

### ISSUE THREAD

**Issue by gregor2004ua** [mosch/react-avatar-editor#272]
I noticed today that the component stopped working on my site. Seems like no matter which part of the image I select the cropper always returns the center of the image. It respects the scale that was selected, but dragging the image to adjust the area cropped has no effect.
Tested on Chrome 70.0.3538.67 and Safari 12.0 (12606.2.11)

It seems to still work properly on my Android Chrome 69.0.3497.100

Can anyone verify if they see same behavior.

Here is my code to handle cropped image and resize it to 500x500
```
handleCrop = () => {
    const canvas = this.editor.getImage();

    let resizedCanvas = document.createElement("canvas");
    let resizedContext = resizedCanvas.getContext("2d");
    resizedCanvas.height = 500;
    resizedCanvas.width = 500;
    resizedContext.drawImage(canvas, 0, 0, 500, 500);
    this.props.handleB64Img(resizedCanvas.toDataURL());
  };
```

**Comment by mtlewis** [comment]
Can you reproduce this in the demo site?  I just tried it in desktop Chrome 70, and it seems to work, since:
* The x & y sliders move around when you zoom and then drag the image, and
* When you hit preview, the correct part of the image appears.

Perhaps this is specific to Chrome on Android?  Unfortunately I don't have an Android device to test with.

**Comment by mtlewis** [comment]
I also just did a quick test with `getImage` (as the demo uses `getImageScaledToCanvas`) - that's working fine for me too.  Please let me know if you have any other tips to reproduce this.

**Comment by gregor2004ua** [comment]
I tried the demo site and it works fine. Must be something with my code, but it worked fine last time i tested it a few weeks ago. Do you see any issues with the code I posted above?

**Comment by gregor2004ua** [comment]
I figured it out. I had two instances of the editor, one that would show up on mobile devices and one for  desktop screens, the appearance was controlled by bootstrap classes. So effectively there were 2 instances in the dom, thats what caused this misbehavior.
