### ISSUE TITLE
Getting cropping rect information for server-side handling

### ISSUE THREAD

**Issue by benjamindulau** [mosch/react-avatar-editor#28]
What public method should I use to get the relative cropping information in case I want to do the actual cropping/resizing server-side?

This would include (x,y) coordinates in the orignal image and the width/height of the cropped rect, being relative to the current scaling.

**Comment by benjamindulau** [comment]
Maybe I can help on this if you lead me ;-)
Where should I add these and what information should I relay on inside the component?

**Comment by mosch** [comment]
I'm currently thinking of removing the semi transparent cropping frame since it causes a lot of trouble. Watch my commit's today. 
If i finished this, all you need is the "this.state.image.x and this.state.image.y" to calculate the cropping frame.

**Comment by babsonmatt** [comment]
How does scale affect this?

**Comment by benjamindulau** [comment]
@mosch Could you give me more details about how to calculate the cropping frame? What would be the formula exactly? Maybe I'm dumb but I don't get how you do it when painting the resulting image in the canvas ;-)

**Comment by mosch** [comment]
@benjamindulau I have been quite busy the last days. 
At the moment we don't calculate s.th. like a cropping frame, but the position of the image on the canvas. 
You need to check the size of the image and calculate were the visible area is. And like @babsonmatt mentioned don't forget to add the scale to the image.

**Comment by hu9o** [comment]
I guess we need to add a ``onImageDrag`` callback prop.
It would get called with some info about the drag event, including the cropping rect.
What do you think ?

**Comment by hu9o** [comment]
I just realized an ``onImageDrag`` prop won't cut it, as the cropping rect should also be updated on zoom...
``onCroppingRectChange`` maybe, or simply ``onChange`` (which would also get called on image load) ?

**Comment by williansebastiao** [comment]
someone managed to find the solution for the crop?

**Comment by williansebastiao** [comment]
did anyone find the solution for the crop?
