### ISSUE TITLE
getImage() not returning cropped image

### ISSUE THREAD

**Issue by BrennonG** [mosch/react-avatar-editor#281]
Not sure what I'm doing wrong here... but can't seem to get getImage() or getImageScaledToCanvas() to return the newly cropped image. They are returning an image, but it's the original image, without the crop. Everything else seems to be working great (converting to dataURL, blob, etc.).  

I guess I just want to confirm that getImage() should indeed return the newly cropped image (canvas), and I shouldn't need to do any further handling?

![screen shot 2018-12-31 at 3 45 05 pm](https://user-images.githubusercontent.com/8673153/50558901-85181b00-0d13-11e9-9882-dd3fcfabc1a0.png)

**Comment by BrennonG** [comment]
One clue that I've stumbled on is when I console.log(getCroppingRect()), the rectangle is very small, less than a pixel in each direction. That got me thinking this must have something to do with scale, but I've toggled everything and still no luck.

**Comment by BrennonG** [comment]
Thx for the quick response! Much appreciated. I'll keep at it over here

**Comment by mtlewis** [comment]
No problem, keep us updated on how it goes!
