### ISSUE TITLE
Background of canvas is black when saving as "jpeg"

### ISSUE THREAD

**Issue by afilp** [mosch/react-avatar-editor#282]

**Comment by afilp** [comment]
See here:

![image](https://user-images.githubusercontent.com/7850073/51187498-a4eb3980-18e4-11e9-994d-798440dd3783.png)

This does not happen with "png", which has a `white` background.

I would like to have `white` background when saving as `jpeg`. Is this supported? Thanks.

My code:
```
  saveCanvasToFile = (format, quality = 1) => {
    const canvas = this.refAvatarEditor.current.getImageScaledToCanvas();

    const linkForSave = document.getElementById('linkForSave');
    linkForSave.download = this.state.outputFilename + '.' + format;
    linkForSave.href = canvas.toDataURL(`image/${format}`, quality);
    linkForSave.click();
  };
```

I use the `format` either as `png` or `jpeg`.

**Comment by afilp** [comment]
I tried to do what this article says here but I then get a plain white image:
https://stackoverflow.com/questions/20744628/how-to-convert-a-image-from-png-to-jpeg-using-javascript

I was doing this inside `paintImage`, should I do it somewhere else?

```
     context.fillStyle = '#fff';  /// set white fill style
     context.fillRect(0, 0, width, height);
```

**Comment by afilp** [comment]
I think I solved the issue but this needs to be added to the lib (optionally), for a color background.

I added the following code in `getImageScaledToCanvas`:

```
    // don't paint a border here, as it is the resulting image
    this.paintImage(context, this.state.image, 0, 1)


    // Draw white background/rectangle on entire canvas
    context.globalCompositeOperation = "destination-over";
    context.fillStyle = "#FFFFFF";
    context.fillRect(0, 0, canvas.width, canvas.height);

    return canvas
```

**Comment by mosch** [comment]
Sure! I'm looking forward for your PR!

**Comment by mosch** [comment]
@afilp are you interested in adding this feature?

**Comment by afilp** [comment]
I am sorry for the delay, I am a little overwhelmed at this phase. 

I will try to do this during the weekend.

**Comment by mosch** [comment]
Alright, let me know if you need some hints!

**Comment by nzkks** [comment]
Hey @mosch, any progress on this feature? I do face this issue. Basically it would be nice to have below props for ReactAvatarEditor. Thanks for the great component.
- export image dimensions
- non-transparent image background
- exported image quality

**Comment by jadus** [comment]
@afilp @mosch , same issue here could you fix this ? Thanks

**Comment by sathvik12345** [comment]
@mosch , same issue here could you fix this ?

**Comment by mosch** [comment]
@jadus @sathvik12345 this repository mainly relies on the community to help working on things. So please feel free to raise a PR. Let me know when you need a hint!
