### ISSUE TITLE
Need disableHiDPIScaling in a release

### ISSUE THREAD

**Issue by dabbe** [mosch/react-avatar-editor#283]
First of all, this is an awesome library that has saved me a lot of hours and headache!

However, I'm getting really, really poor performance on my phone (Samsung Galaxy S8) with a 1100x500px canvas. (I would like to just display like 275x125px canvas on phone, but since the canvas size can't be defined with css - correct me if I'm wrong - I'm stuck with the same canvas regardless of screen size).

Then I found `disableHiDPIScaling` which I wanted to try out. Unfortunately, it wasn't included in the 11.0.4 release, and there hasn't been a release since.

Release: https://github.com/mosch/react-avatar-editor/releases/tag/v11.0.4
Commit: https://github.com/mosch/react-avatar-editor/commit/147544d13de83c82e12831bc6faff0aa3cca9a17

**Comment by mosch** [comment]
Its in here: https://github.com/mosch/react-avatar-editor/releases/tag/v11.0.5
