### ISSUE TITLE
Feature Request: Crop 2 images(background-image and image) into a single output image.

### ISSUE THREAD

**Issue by svenkatesh-nyros** [mosch/react-avatar-editor#284]
Is it possible to provide the source image in a existing background image to crop them into single image using this package.
following is the example working urls for making this feature.

http://subinsb.com/create-profile-picture-framer-web-app/

Git url: https://github.com/subins2000/profile-picture-framer

can this feature implemented in your package ?

**Comment by mosch** [comment]
Hi @svenkatesh-nyros , this is not one of the features that we would implement in our library. However you can implement it yourself using a callback on the context. If we provide you a **onPain** callback that passes you the context, you are able to paint in on the current image yourself.
