### ISSUE TITLE
Responsive canvas

### ISSUE THREAD

**Issue by ryuran** [mosch/react-avatar-editor#287]
Hello,
I need the canvas responsive but width and height are set in inline style.
Add feature or for make the canvas element responsive or document how to do.

**Comment by mosch** [comment]
Hey @ryuran – that would be great. Just raise a PR if you are looking to add this feature to this library.

**Comment by MatteoGioioso** [comment]
I don't know if this can help but I have solved like this:
wrap the component in a `div` and give it this style 
```
rootDiv: {
    width: "100%",
    height: "100vh",
    textAlign: "center",
    display: "grid"
  },
```
then on the `canvas` / `Editor`
```
  canvas: {
    width: "100%",
    height: "auto",
    maxWidth: "100vh",
    margin: "auto"
}
```

In this way the canvas maintain aspect ratio and it is responsive
