### ISSUE TITLE
no way to prevent overflow

### ISSUE THREAD

**Issue by adamweup** [mosch/react-avatar-editor#288]
It seems impossible to wrap the canvas element that is displaying the image in an overflow hidden div? This is not really a usable lib if resizing the picture is always going to cause it to balloon through the entire UI and cover the page. Is there any work around for this?

**Comment by mosch** [comment]
Hey @adamweup , I'm sorry to heart that this library doesn't fit your usecase. Hover it act's like any canvas element and you should be able to use overflow hidden with it.
If you provide your [an example of your use-case](https://codesandbox.io/) we might be able to help.
