### ISSUE TITLE
Unable to get cropped image error in .toDataURL()

### ISSUE THREAD

**Issue by karan-clixlogix** [mosch/react-avatar-editor#289]
Not  sure why I am getting an error while using .toDataURL()

When I used with an uploaded image from system its working 

 
![error](https://user-images.githubusercontent.com/47345124/54276956-92c00b80-45b4-11e9-88be-4dc249a3cd0b.png)

`const canvas = this.editor.getImage().toDataURL()
`
But when i used image from url, getting error with toDataURL()

`SecurityError: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.`

**Comment by dan-lee** [comment]
Possible duplicate of https://github.com/mosch/react-avatar-editor/issues/168. Can you check please?
