### ISSUE TITLE
Empty image when crossOrigin is seted to "anonymous"

### ISSUE THREAD

**Issue by franciscojfs** [mosch/react-avatar-editor#291]
Hello!

To  be able of upload the resulting image, I have added the "crossOigin" prop to my editor.

```javascript
<AvatarEditor                        
    width={164}
    height={150}
    border={5}
    color={[255, 255, 255, 0.6]} // RGBA
    crossOrigin= "anonymous"
    ref={props.profilePictureEditor}
    image={props.profilePicture}
    scale={props.profilePictureScale}
    rotate={props.profilePictureRotate}
    borderRadius={props.profilePictureBorder}
/>
```

```javascript
profileOnSave={() => {
    this.props.profile.save(this.state.profileTitle, this.state.profileDescription)
    
    var canvasScaled = this.editor.getImageScaledToCanvas()
    canvasScaled.setAttribute('crossOrigin', 'anonymous')
    
    this.props.profile.updatePicture(canvasScaled.toDataURL('image/jpg'))
}}
```

However, all images that I tried to use as a source were not presented. Even those that didn't came from my firebase storage, like the bellow:

https://www.keephealthyliving.com/wp-content/uploads/2018/04/psychologist-holding-picture.jpg

The images came back if I remove the "crossOigin" prop. Should I do anything else to use this correctly?

**Comment by mosch** [comment]
You can find [more information about this here](https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image).

If it works without providing the prop – why would you?

**Comment by franciscojfs** [comment]
I'm getting the image by the 'this.editor.getImageScaledToCanvas()' method, and getting that error. Providing the prop was needed to stop receiving that error, but the image goes blank . Doesn't it looks like an error on the component?

**Comment by TITAN9389** [comment]
getting same blank image when setting crossOrigin to anonymous , what is the solution for this ? without setting the crossOrigin i get insecure issue.

**Comment by Zegoverno** [comment]
same here! How do you overcome this?
