### ISSUE TITLE
Get output as a file

### ISSUE THREAD

**Issue by ViuLive** [mosch/react-avatar-editor#293]
I'm using react-avatar-editor to edit and upload image files.
Now I'm getting the file from the input and send it to the editor and implement the edits on the file, But I expect to get a file from the output, not the URL, to send it to the server. 
How can I do that?

**Comment by ViuLive** [comment]
I've found the way, it should be like that

```
handleOk = () =>{
      if (this.editor) {
        const img = this.editor.getImageScaledToCanvas()
        img.toBlob(blob=>{
          if(blob){
           this.setState({
            file:URL.createObjectURL(blob), //create object url to show the edited image
           })
           this.props.value(blob)  //return value as file
          }
        })
      }
    }
    setEditorRef = (editor) => this.editor = editor


```

**Comment by mosch** [comment]
Im glad to hear that you found a solution!

**Comment by quannguyennn** [comment]
Im trying to replica your solution but ran into a bug that **SecurityError: Failed to execute 'toBlob' on 'HTMLCanvasElement': Tainted canvases may not be exported.**. 
I also read about this bug before and try to set the canvas attribute crossorigin = anonymous but nothing change

**Comment by yamanidev** [comment]
@ViuLive Could you please elaborate the solution you shared? It seems that it's creating a URL from the blob, but not a file as the issue's title suggests, no?
