### ISSUE TITLE
Edited images gain size

### ISSUE THREAD

**Issue by Carian-ayoub** [mosch/react-avatar-editor#294]
I have a form where I want to upload a few fields and an image. 
After editing the image and extracting the edited image from canva, i noticed a big file size increase, wish i suspect is due to the function "toDataURL".

`
                const scaledImage = this.editor.getImageScaledToCanvas().toDataURL('image/png').substring(22)
`

**Comment by hamidra** [comment]
Did you try getImage() instead of getImageScaledToCanvas(). From the doc seems getImageScaledToCanvas() is legacy method and will resize the image to the canvas size.

**Comment by Carian-ayoub** [comment]
Yes, I tried it.
The problem is the conversion from a canva to an image using toDataURL doesn't preserve the original resolution but has a standard one of 96dpi. 
I wonder if there's anyway to avoid using canvas.

**Comment by yaroslav-nuznenko-axon** [comment]
Have the same issue when use `getImage` func.
