### ISSUE TITLE
When images are not the exact same height and width radius cannot create a perfect circle.

### ISSUE THREAD

**Issue by GeorgiosP** [mosch/react-avatar-editor#296]
https://www.loom.com/share/fe75819b9eee4948acba67fefe6e5acf

**Comment by mosch** [comment]
Thank you for sharing this. I guess it's something between a bug and an enhancement 🥴

**Comment by GeorgiosP** [comment]
Yeah its a bit strange, I should have some time on the weekend if not sooner to take a look at this if you like! 😃

**Comment by mosch** [comment]
@GeorgiosP sure – that would be great!

**Comment by hu9o** [comment]
@GeorgiosP Have you tried setting the border sizes so the cropping area remains square (even though the editor area is not)? I think that would solve the issue.

**Comment by GeorgiosP** [comment]
@hu9o its what i ended up doing, but it doesn't look great with images that have if non square aspect ratio its fine if your image has the same background as your border tho.

**Comment by mtlewis** [comment]
Hey @GeorgiosP - would you mind describing in more detail what your expected behavior is here please? Do you want to be able to create an elliptical image by increasing the border radius of the long side when the short side’s border radius hits 50%?

If you could find some example image that demonstrates what you’re looking for, that would be super helpful. Thanks!

**Comment by GeorgiosP** [comment]
Hey @mtlewis, sure I can explain expected behavior. 

here is a good example below with a photo editor you can see the canvas hight and width are not exactly the same but you can still have a crop circle. and not an oval.

https://cl.ly/fa30cdc35f28

When a canvas is set to non square dimensions like width 500 and hight of 250 image crop circle should be able to be circular and not an oval. this is for display purposes so users can see their entire image and adjust it accordingly. 

currently you can work around this by expanding the border of a square canvas to fake the rectangle shape but if the users image background is not transparent or white it will look strange and not meet the layout of the example above. 

I'll actually be able to work on this now I've got some free time since I've wrapped up all my contract work. but if you want to take it on go for it! 😄 

let me know if you have anymore questions 👍

**Comment by mtlewis** [comment]
Thanks, that's really helpful! I started playing around with ideas for fixing this in #304. In short, we could start accepting canvasWidth & canvasHeight props, and use them instead of the border if they're set.
