### ISSUE TITLE
Rotating image flips aspect ratio

### ISSUE THREAD

**Issue by jonlambert** [mosch/react-avatar-editor#299]
When rotating an image in the editor, it seems to flip the canvas width and height values when the scale property is either 0 or multiples of 180, in which case it flips back to the original values.

I can see a few related issues (namely #183), but can't seem to work out what the best workaround to this is. Any advice would be greatly appreciated.

**Comment by tnguyengamelink** [comment]
this worked for me    

handleRotateCCW = () => {
        this.setState({
            rotate: this.state.rotate - 90,
            width: this.state.height,
            height: this.state.width
        })
    }

    handleRotateCW = () => {
        this.setState({
            rotate: this.state.rotate + 90,
            width: this.state.height,
            height: this.state.width
        })
    }

**Comment by mosch** [comment]
Well, that's an odd behaviour. Let's call it a bug.

**Comment by nioe** [comment]
I experience the same bug currently. For all angles other than 0° and ±180° the horizontal aspect ratio is flipped...
While digging a bit through the code I stumbled over the [`isVertical()`](https://github.com/mosch/react-avatar-editor/blob/master/src/index.js#L305) function which I think is the culprit of the problem. The function is called within [`getDimensions()`](https://github.com/mosch/react-avatar-editor/blob/master/src/index.js#L323) where the view is flipped. :) Hope that helps a bit.
