### ISSUE TITLE
React Avatar Editor in stateless component

### ISSUE THREAD

**Issue by yleyvag** [mosch/react-avatar-editor#307]
How can I use this component inside any react stateless component? I can't use 'this'. I tried with
```const setEditorRef = useRef()```
```•••```
```const savePicture = () => {```
```    if (setEditorRef){```
```    const canvas = setEditorRef.getImage()```
```    }```
```}```
But I'm receiving error setEditorRef.getImage is not a function.
I tried printing "setEditorRef" and I can see all the properties from the object but there's no getImage() function.

**Comment by yleyvag** [comment]
For the record, the solution is
```const canvas = setEditorRef.current.getImage()```

**Comment by moeabdol** [comment]
Hi @yleyvag `getImage does not exist on type never` any idea?

**Comment by moeabdol** [comment]
For those using TypeScript
```
const editorRef = useRef<AvatarEditor | null>(null);
•••
if (setEditorRef.current) {
    const canvas = setEditorRef.current.getImage();
}
```
