### ISSUE TITLE
Failed to execute 'toBlob' on 'HTMLCanvasElement': Tainted canvases may not be exported.

### ISSUE THREAD

**Issue by stevenhales** [mosch/react-avatar-editor#308]
Hi guys, 

```
this.editor.getImageScaledToCanvas().toBlob(blob => {
        this.props.uploadProfileImage(blob);
});
```

I am experiencing an issue converting to blob. It occurs when I crop an image, upload it to my server, make the "image" attribute of the cropper point to this new image, then try to crop the resulting image again. 

I saw that there was a previous closed issue where someone was getting the same error when converting to base64. But I can't see a way to use the solution for that one here. Can you offer any support? Thank you.

**Comment by mosch** [comment]
Hey @stevenhales – is the server you upload to running the same domain as the website you crop in?
Check out [this post on stackoverflow](https://stackoverflow.com/questions/22710627/tainted-canvases-may-not-be-exported) to get a better understanding of how this happens.
