### ISSUE TITLE
[HELP] how can i get the circle image data ?

### ISSUE THREAD

**Issue by TITAN9389** [mosch/react-avatar-editor#309]
i'm trying to crop the image into Circle , giving 100 border radius on Editor just giving me the UI of it , when i'm checking the image after crop `getImageScaledToCanvas()`  i still get Square image, how can i achieve Circle image with Transparent Background ?

**Comment by mosch** [comment]
Hey @TITAN9389 – this is currently not supported. Also I would not recommend you to do this. Just keep the full image, and reproduce the effect with css (border-radius)!

I hope this helps.
