### ISSUE TITLE
There is a little red dot in the top left corner of the canvas area

### ISSUE THREAD

**Issue by jtsk** [mosch/react-avatar-editor#311]
There is a little red dot in the top left corner of the canvas area

**Comment by sambecker** [comment]
I'm also seeing this! Any ideas?

**Comment by stefanfuchs** [comment]
I have the same problem here, but setting `disableHiDPIScaling={true}` did not work.

**Comment by cizhijingli664** [comment]
Did someone solve it？

**Comment by epgui** [comment]
I'm getting this as well, and I'm wondering if it has to do with how the editor parses the MIME type at the beginning of the data URI string?

**Comment by StephenKoller** [comment]
Not sure if this is helpful, but I realized that it wasn't happening in the demo and did some digging.

Turns out it's only happening in the beta version, not the latest stable (11.0.7). Try reverting to latest stable version and see if that fixes your issue.

If this issue is opened for continued development on the beta, then please ignore this and carry on. 😛

**Comment by yanickrochon** [comment]
The red dot is still there in 11.0.7 for me. I have tried to locate the problem by reading the code, but I have no idea what could cause this. The worst part is that it scales with the image! It's as if a rogue pixel was set when copying the i mage unto the canvas.

**Comment by LukePammant** [comment]
> The red dot is still there in 11.0.7 for me. I have tried to locate the problem by reading the code, but I have no idea what could cause this. The worst part is that it scales with the image! It's as if a rogue pixel was set when copying the i mage unto the canvas.

It worked for me - try making sure to remove the old package from your node_modules first.

**Comment by naveensomanna** [comment]
There is extra space on the top and bottom of the canvas how to fix it

**Comment by ridl27** [comment]
still no fix ?

**Comment by naveensomanna** [comment]
No i found another library which solved the problem

**Comment by sambecker** [comment]
Which library did you end up using?

**Comment by naveensomanna** [comment]
react-easy-crop

**Comment by nodtem66** [comment]
The latest commit in master branch (47ca882) seems fine to me.
In the codesandbox testing, there's no warning issues about `UNSAFE_*` as in the `11.0.7`
[codesandbox.io](https://codesandbox.io/s/elastic-shaw-wcdw1?fontsize=14&hidenavigation=1&theme=dark)

However, the `12.0.0-beta.0` has a lot of buggies.

**Comment by chrisgwgreen** [comment]
Unusually, version `12.0.0-beta.0` on line 425 of `https://github.com/mosch/react-avatar-editor/blob/v12.0.0-beta.0/src/index.tsx` adds the red square if an image is present?!

I reverted to `11.0.*`.

**Comment by syedzubairahmed001** [comment]
iam also getting the same issue :(

**Comment by mycolaos** [comment]
`Unusually, version 12.0.0-beta.0 on line 425 of https://github.com/mosch/react-avatar-editor/blob/v12.0.0-beta.0/src/index.tsx adds the red square if an image is present?!`
@mosch what? 😄

**Comment by yanickrochon** [comment]
@mycolaos I believe what he's saying is that the current version on npm is **12.0.0-beta.0**, where `master`, here, is **11.0.7**. Looking into the npm-published branch, we can indeed find a red dot being drawn at the top-left corner of the image.

https://github.com/mosch/react-avatar-editor/blob/f9eca9c1321fc6142d49baa16f50a4f279ba289f/src/index.tsx#L425-L428

**Comment by mycolaos** [comment]
@yanickrochon yeah, I know. My comment was addressed to @mosch which is the author of that lines of code.

**Comment by PichuPerez** [comment]
It worked for me downgrading to 11.0.7 version. Yarn remove and then yarn add @11.0.7

**Comment by mtlewis** [comment]
@mosch, maybe worth republishing the v12 beta version with a "beta" dist-tag instead, and republishing something pre-v12 with the "latest" tag so people don't run into this so much.
