### ISSUE TITLE
getImage() returns cropped image from 0,0px in beta release

### ISSUE THREAD

**Issue by gaurav5430** [mosch/react-avatar-editor#312]
`getImageScaledToCanvas()` returns the correctly cropped image, but `getImage()` doesn't. `getImage()` returns the image cropped from 0,0. The size of the crop is fine.

I am not able to recreate this issue in codesandbox as 12.0.0-beta.0 is not loading in codesandbox.

Here is a sandbox with the stable version which does not have this issue. 
https://codesandbox.io/s/react-avatar-editor-vxodd

If you can somehow load the beta version in codesandbox, you might recreate the `getImage()` issue. 

I had this issue in my codebase and it was resolved by going back to the stable release.

**Comment by tibotiber** [comment]
I'm seeing the same thing. Also, not sure if you mean for this to be the case but `latest` points to the beta version, not the last stable one.

**Comment by gaurav5430** [comment]
Yes, i am having these issues with the beta version but explicitly depending on the last stable release (11.x) seems to work fine

**Comment by tibotiber** [comment]
yes that's why i've done. And thanks for this issue, save me hours of debug :)

**Comment by harshaljhaveri** [comment]
Hi @gaurav5430, can you please provide which version (patch for v11) are you using? Looks like `Stable` tag was updated in last few days. Thanks!

**Comment by AddChan** [comment]
Thanks, I solved it. 😁

**Comment by tomasdivito** [comment]
Hey @AddChan I'm having the same issue, would you mind actually sharing what have you done to fix the issue?
