### ISSUE TITLE
How do I extract the actual size and information about the cropping area?

### ISSUE THREAD

**Issue by 2DSharp** [mosch/react-avatar-editor#316]
The `getCroppingRect()` method returns values 0 to 1 relative to the image, but what is the relation and how do I find the following information: the absolute origin(x, y) and width, height of the image and not a relative value from 0 to 1 so that I can pass it to the server.

I tried something like this but it doesn't seem to work:

```
   const image = this.editor.getImage();
    const rect = this.editor.getCroppingRect();
    let croppedData = {
      x: image.width * rect.x,
      y: image.height * rect.y,
      width: image.width * rect.width,
      height: image.height * rect.height
    };
```
This should result in a square (I have that set in the editor's props) but it doesn't and one side is always bigger than the other.

**Comment by 2DSharp** [comment]
Okay seems like this happens because image.width doesn't give me the actual width, but rather a stripped down width, so 6000x4000 is converted to something like 2600x4000 for some reason. How do I get the actual width of the image?

**Comment by ningappa** [comment]
@2DSharp @mosch Any solution or workaround suggestions? I'm also looking for the information.
