### ISSUE TITLE
Issue with image position after image rotate to deg 90 or 270

### ISSUE THREAD

**Issue by bnayak0225** [mosch/react-avatar-editor#319]
There is a issue with image position after image is rotate to 90 or 270 deg, When i try image to drag top image moves to bottom instead of image moved to top. Its like invert mouse action.

**Comment by zozich** [comment]
Same for me. I was fixing rotation of the image on iOS with `exif-js` using code snippets from the `handleNewImage()` function here https://github.com/innoist/PictureEXIF/blob/master/src/components/HomePage.js. The solution works fine except that vertical image drag controls are inversed. When I drag down, the image moves up, and vice versa. Seems like a problem in the library.
