### ISSUE TITLE
Issue when vertically move rotated on 90deg image

### ISSUE THREAD

**Issue by denis-597** [mosch/react-avatar-editor#323]
Hey guys,
I upload and rotate image on 90 deg for example, but when try to move vertically the image, it's moving to the wrong side. 

![avatarissue](https://user-images.githubusercontent.com/13433025/73825133-1786ca00-4804-11ea-8b4b-256b7d702d58.gif)

**Comment by mosch** [comment]
What version are you using?

**Comment by avillarubia** [comment]
Good day @mosch 
I am using version 12.0.0-beta.0

**Comment by denis-597** [comment]
I am using also:
`"react-avatar-editor": "^12.0.0-beta.0",`

Yesterday I updated with `npm update`

**Comment by hejrobin** [comment]
Same issue for me. Had to downgrade to `v11.0.6`, but it has deprecared code (`componentWillRecieveProps`).

**Comment by jpodpro** [comment]
having the same problem

**Comment by vrahikka** [comment]
Having same issue
