### ISSUE TITLE
Horizontal and Vertical positioning issues

### ISSUE THREAD

**Issue by avillarubia** [mosch/react-avatar-editor#324]
Good day

### Issue
I have this issue only when applying horizontal and vertical positioning.

I use version 12.0.0-beta.0

The gif below shows the example issue
[https://i.imgur.com/TmjtIXm.gifv](url)

### Codes
To display the cropped image

```
    const onClickSave = () => {
        if (editor) {
            const canvas = editor.getImage().toDataURL();
            fetch(canvas)
                .then(res => res.blob())
                .then(blob => {
                    setImageUrl(window.URL.createObjectURL(blob))
                });
        }
    }
```

`<img src={imageURL} style={{ width: '200px', height: '200px', borderRadius: '250px' }} />`

below is the editor
```
        <AvatarEditor
            ref={setEditorRef}
            position={{ x: horizontal, y: vertical }}
            borderRadius={250}
            rotate={rotate}
            scale={scale}
            image={file} />
```

thank you.

**Comment by MrHus** [comment]
It is indeed broken.
