### ISSUE TITLE
Getting Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `App`.

### ISSUE THREAD

**Issue by mdebeus** [mosch/react-avatar-editor#325]
React version installed: 16.8
I don't think react-avatar-editor 12.0.0beta is compatible with React 16.8 hooks.
So I would either fix this wonderful component to be compatible with React 16.8 or change the project.json file to specify < 16.8 instead of 17.0.

**Comment by ville-rahikka** [comment]
I'm getting same with React version 16.6.3. Is there any way to get this to work with new versions of React?

**Comment by ville-rahikka** [comment]
This worked for me:

`import React from 'react';
import AvatarEditor from 'react-avatar-editor';

class MyEditor extends React.Component {
  render() {
    return (
      <AvatarEditor.default
        image="http://example.com/initialimage.jpg"
        width={250}
        height={250}
        border={50}
        color={[255, 255, 255, 0.6]} // RGBA
        scale={1.2}
        rotate={0}
      />
    )
  }
}
export default MyEditor;`
