### ISSUE TITLE
React 16.9.0 deprecated lifecycle method warning

### ISSUE THREAD

**Issue by stefanzmf** [mosch/react-avatar-editor#327]
Using `react-avatar-editor` with 16.9.0 throws this warning. 

```
Warning: **componentWillReceiveProps** has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: l
```

![Screenshot 2020-03-03 at 13 07 17](https://user-images.githubusercontent.com/1851658/75770234-4420f980-5d50-11ea-82e0-12694331666e.png)

**Comment by JelouSoft** [comment]
Same problem

**Comment by Ralk** [comment]
Same problem here, do you plan to do something?

**Comment by rex-pj** [comment]
Same problem here, will it fixed in any plan?

**Comment by nigel-daniels** [comment]
Hi I am seeing this in 16.0.9, I had to downgrade from 16.0.10 because of #340 so I am not sure if this was fixed in that release.

**Comment by rex-pj** [comment]
> Hi I am seeing this in 16.0.9, I had to downgrade from 16.0.10 because of #340 so I am not sure if this was fixed in that release.

I was change "react-avatar-editor": "^11.0.10" => "react-avatar-editor": "11.0.9" (**Remove ^**) and it is now working fine.

**Comment by dan-lee** [comment]
Should be resolved by the latest version(s).
