### ISSUE TITLE
Editable shape of the crop

### ISSUE THREAD

**Issue by oyeanuj** [mosch/react-avatar-editor#330]
Hi @mosch, back again as I'm integrating it with another project! 

I'm curious it is possible to let the user create the crop shape rather than giving a pre-determined width and height? So, a user could create a square crop or rectangular crop?

Apologies if I missed this option that already exists!

**Comment by mtlewis** [comment]
Hey @oyeanuj - I think you could probably do this by providing controls external to the avatar editor that are attached to its width and height props, and allowing the user to edit them. There's an example of this in the demo.
