### ISSUE TITLE
Crop image

### ISSUE THREAD

**Issue by williansebastiao** [mosch/react-avatar-editor#331]
Hello!
How do I capture width, height, x and y to crop with php?

**Comment by hu9o** [comment]
See https://github.com/mosch/react-avatar-editor/issues/28

**Comment by mtlewis** [comment]
See also the ["accessing the cropping rectangle" section of the README](https://github.com/mosch/react-avatar-editor#accessing-the-cropping-rectangle).

**Comment by williansebastiao** [comment]
I read ... but when sending the coordinates: x, y and width and height the image crop is not correct.
