### ISSUE TITLE
Get image full size returns error

### ISSUE THREAD

**Issue by PichuPerez** [mosch/react-avatar-editor#334]
Hi @mosch Im trying to get the image in the canvas in its original size. I had to downgrade to version 11.0.7 because of the red dot issue. But now getImage() is returning an error. I also tried with the lates version, the one that has the red dot issue but doesn't work.

`TypeError: Cannot read property 'width' of undefined`

**Comment by DDroll** [comment]
@PichuPerez, its not a thing, witch we call solution, but i had found a workaround. Just wrap block with "getImage" in "try-catch" block and all works fine. But error is still here.

**Comment by PichuPerez** [comment]
@DDroll thanks, i ended up forking the repo and changing things my self since its not maintained.

**Comment by mosch** [comment]
@PichuPerez PR more thank welcome!

**Comment by PichuPerez** [comment]
@mosch sorry i thought it would never be updated, there is a bunch of things i changed it to customize it specifically for my app, i dont know it it will work.

**Comment by mosch** [comment]
@PichuPerez It may take some work to remove the code that is specific to your app, however, it will be worth it if others can reuse what you did! Let me know if can help you with doing so.
