### ISSUE TITLE
Support for < 1 scale?

### ISSUE THREAD

**Issue by babsonmatt** [mosch/react-avatar-editor#34]
Seems to go a lil crazy if you try to set min scale to anything below 1 (if it drops the image size to be smaller than the editor window).

**Comment by mosch** [comment]
@babsonmatt Is there a use case for scale < 1?

**Comment by dan-lee** [comment]
What exactly are you trying to achieve? You will get white space around your "cropped" (zoomed out) image.

**Comment by mosch** [comment]
closing this, feel free to comment if you still looking forward to this
