### ISSUE TITLE
ReferenceError: babelHelpers is not defined

### ISSUE THREAD

**Issue by martin8877** [mosch/react-avatar-editor#340]
Hi,
library is not working after latest upgrade 11.0.10

`react-avatar-editor/dist/index.js:125`
```
  122 |   y: .5
  123 | },
  124 |     i = function (e) {
> 125 |   babelHelpers.inherits(i, e);
      | ^  126 |   var t = n(i);
  127 | 
  128 |   function i(e) {
```

**Comment by sambecker** [comment]
Saw this error deploying my `nextjs` app to `vercel`.

Reverting back to `11.0.9` resolved the issue.

**Comment by tianliuj** [comment]
I have the issue in 11.0.9，how should i do

**Comment by camux** [comment]
I had this issue just works fine with 11.0.7

**Comment by Alexey-Khlebnikov** [comment]
How are you, @camux?
> I had this issue just works fine with 11.0.7

Could you please let me know where is version 11.0.7?

**Comment by Alexey-Khlebnikov** [comment]
Ah, I used version 11.0.7 in package.json file.
![image](https://user-images.githubusercontent.com/48479239/87882424-45269f00-ca43-11ea-92e1-b8544da681f3.png)

It works well now.
Thank you very much.

**Comment by ianpogi5** [comment]
We've also experienced this issue. Reverting back to `11.0.9` fixes the problem.

We did it by removing the caret from the version number. If not, it will always default to `11.0.10`.

**Comment by ahmetcetin** [comment]
the same here, 11.0.10 crashes with "babelHelpers is not defined", reverting back to 11.0.9 fixes the problem

**Comment by crscaballero** [comment]
Exactly same problem on `11.0.10` version

**Comment by henryjin3** [comment]
Could be related to https://github.com/babel/babel/issues/9366

**Comment by eprincen2** [comment]
I still have the problem reverting back to 10.0.7. Even removed yarn.lock and node_modules and did a yarn cache clean and a fresh yarn install. I've seen the following piece of advice posted elsewhere, but I'm unclear if it's applicable and I don't have the time right now to look into it: https://github.com/babel/babel/issues/9366#issuecomment-455748788

**Comment by gaurav5430** [comment]
For now i have pinned down my version to 11.0.7

**Comment by qooqpoop** [comment]
Having this issue on Ubuntu as well. Reverting it to 11.0.7 isn't working as well.

The error message says:

×
ReferenceError: babelHelpers is not defined
(anonymous function)
node_modules/react-avatar-editor/dist/index.js:1

**Comment by eprincen2** [comment]
> Having this issue on Ubuntu as well. Reverting it to 11.0.7 isn't working as well.

Make certain you are actually reverting. My initial attempt to revert did not revert. Once I noticed and fixed the issue, it worked perfectly. Make sure package.json in node_modules/react-avatar-editor begins with:

{
  "name": "react-avatar-editor",
  "version": "11.0.7",

**Comment by tegozen** [comment]
```rm -rf node_modules``` and https://prnt.sc/tv0wk8
**resolve for me**

**Comment by astroana** [comment]
Though reverting back to 11.0.9 or 11.0.7 removes the 'babelHelpers is not defined' error but instead gives me back the old warning:

**componentWillReceiveProps** has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

**Comment by jvlobo** [comment]
Same issue here. Also fixed by reverting back to 11.0.9

**Comment by DonovanCharpin** [comment]
Same issue, reverting back to 11.0.9 fixed it!

**Comment by sonam-diwate-invimatic** [comment]
Still not working with 11.0.9

**Comment by Bonjur** [comment]
WTH update the package, it's been a year @mosch

**Comment by sergeu90** [comment]
Hello everyone. When will fix it problem?

**Comment by buzztaiki** [comment]
I see PR #343 includes fix of this issue, but not released yet.

**Comment by thesiti92** [comment]
@mosch please make a new release with the fix! ill buy you a pint :)

**Comment by mosch** [comment]
Just released 10.0.11 - can u confirm?

**Comment by sergeu90** [comment]
@mosch After update i still getting issue

**Comment by sambecker** [comment]
Thanks for looking into this @mosch.

Still seeing the same issue.

Pretty wild to see babel crashes in runtime? Don't think I've seen that before ...

<img width="982" alt="Screen Shot 2020-10-23 at 3 32 36 PM" src="https://user-images.githubusercontent.com/169298/97051684-35888c00-1545-11eb-984e-89d032cb1ffd.png">

```
index.js?5502:1 Uncaught (in promise) ReferenceError: babelHelpers is not defined
    at eval (index.js?5502:1)
    at eval (index.js?5502:1)
    at eval (index.js?5502:1)
    at eval (index.js?5502:1)
    at Object../node_modules/react-avatar-editor/dist/index.js (profile.js:4392)
    at __webpack_require__ (webpack.js?ts=1603485095804:873)
    at fn (webpack.js?ts=1603485095804:151)
    at Module.eval (AvatarEditor.tsx:4)
    at eval (AvatarEditor.tsx?9c52:153)
    at Module../components/AvatarEditor.tsx (profile.js:201)
    at __webpack_require__ (webpack.js?ts=1603485095804:873)
    at fn (webpack.js?ts=1603485095804:151)
    at Module.eval (ProfileSettings.tsx:22)
    at eval (ProfileSettings.tsx?42de:261)
    at Module../user/ProfileSettings.tsx (profile.js:5575)
    at __webpack_require__ (webpack.js?ts=1603485095804:873)
    at fn (webpack.js?ts=1603485095804:151)
    at Module.eval (profile.tsx:4)
    at eval (profile.tsx?6ed7:13)
    at Module../pages/profile.tsx (profile.js:5456)
    at __webpack_require__ (webpack.js?ts=1603485095804:873)
    at fn (webpack.js?ts=1603485095804:151)
    at eval (next-client-pages-loader.js?5198:5)
    at register (page-loader.ts?6f7a:366)
    at eval (page-loader.ts?6f7a:438)
```

**Comment by SergeyKorotaev** [comment]
too ((

**Comment by mmaloon** [comment]
Looks like the dist/index.js is the exact same in 11.0.10 and 11.0.11.  Did you forget to re-build the dist file?

**Comment by mosch** [comment]
Re-Published .**Try 11.0.12**

**Comment by sambecker** [comment]
Worked for me @mosch! 🙏 🙏 🙏

**Comment by mosch** [comment]
Thank you for verifying. Sorry for being unresponsive!

**Comment by thesiti92** [comment]
@mosch you just saved us a bunch of dev headache, thanks. do you have a buy me a coffee or venmo? i was serious about the beer 😆

**Comment by maxmatthews** [comment]
Ditto, I'll buy the second round 😜

**Comment by mosch** [comment]
Thanks, I appreciate it! However, just help me keep this thing maintained by pointing me to the most important needs instead.

**Comment by thesiti92** [comment]
lit, thanks dude!
