### ISSUE TITLE
The demo is not rendering anymore

### ISSUE THREAD

**Issue by RaymondMwaura** [mosch/react-avatar-editor#345]
The demo for the npm package hosted [here](https://react-avatar-editor.netlify.com/) is not rendering anymore. I think it might be because of a missing resource. Here's the error message:

`Failed to load resource: the server responded with a status of 404 ()`

**Comment by mmlumba** [comment]
Also experiencing the same issue

**Comment by johnbonds** [comment]
confirmed, demo isn't working.

**Comment by dan-lee** [comment]
Thanks! Fixed in #350 🚀
