### ISSUE TITLE
Support for gifs and their editing?

### ISSUE THREAD

**Issue by IgnusG** [mosch/react-avatar-editor#351]
After we've integrated the editor  I've realized that with gifs, only a single frame is rendered, which can then be edited and saved but the rest of the gif gets lost. 

It would be really cool if it was possible to render all the gif frames onto the canvas (and play them - switch between them like a normal gif). Saving the changes (after cropping) would then return an adjusted gif instead of an adjusted static image. 

This would probably be best done by using a library for handling the canvas gif rendering - although I haven't found one that's well maintained so far. Otherwise I  imagine the rest of the editor wouldn't need any breaking changes to accommodate this behavior?

**Comment by IgnusG** [comment]
Bump

**Comment by mosch** [comment]
Thanks for your issue. I think this can (and should) be implemented in user-land. Just pass in the current frame into the editor and when you save it's up to you to apply the changes to all frames. I don't see it as part of this library.

**Comment by GitKokoszka** [comment]
Hey @mosch. Could you elaborate on implementing it in user-land? I mean when I pass the `image/gif` type file to `<Avatar>` and then immediately get it back from it with:
```
const content = cropperRef.current.getImage().toDataURL('image/gif');
``` 
the content after passing it to `<img>` tag is static and I can see from chrome's Application>Frames>Images that it is `image/png` type indeed:
![image](https://user-images.githubusercontent.com/46566764/193455612-4c4fcc25-1c77-4eba-a177-f87fe306c4e7.png)
The other, correct `image/gif` comes from reading file from system, before passing it to `<Avatar>`.
Clearly there is something happening under the hood, where `image/gif` info is lost in the process. I may be wrong too in the whole process - if so, could you help me get it to work?
