### ISSUE TITLE
Can not drag image in Mobile device

### ISSUE THREAD

**Issue by hophacker** [mosch/react-avatar-editor#36]
If you open react avatar editor in mobile device(or turn on mobile debugging in Chrome), the image is not dragable. Error as: `Uncaught TypeError: Cannot read property 'files' of undefinedReact.` at line `302`

**Comment by mosch** [comment]
Works fine in current version, can you validate this bug on http://mosch.github.io/react-avatar-editor/ ?

**Comment by dan-lee** [comment]
The error still occurs, but is related to the drag/drop events which are linked to `onTouchMove`/`onTouchEnd`. The actual problem described by OP however was fixed within 
https://github.com/mosch/react-avatar-editor/commit/216c5084f50021afce2a356b0550a9759a219ca4 and should work now.
