### ISSUE TITLE
can you provide the data not as base64 but as file?

### ISSUE THREAD

**Issue by Boby** [mosch/react-avatar-editor#360]
Hi, I was trying to use it but can we provide the crop finished as files.append instead of base64?

**Comment by AfonsoRCR** [comment]
Hey Boby. I struggled with this too. I found lots of different and incomplete answers and mashed them together ended up with something like this:

 ```
    const img = editor.getImageScaledToCanvas().toBlob(
      (blob) => {

        const file = new File([blob], `profilePicture.png`, {
          type: "image/png"
        });
        
        var formData = new FormData();

        formData.append("file", file)

      })

```

**Comment by tomaszbakula** [comment]
@AfonsoRCR - The presented solution works, but its downside is that it significantly increases the size in kb of the image. In my case, the size increased from 0.5 to 3.3 MB.
