### ISSUE TITLE
Is it possible to show nothing outside the crop area?

### ISSUE THREAD

**Issue by nandorojo** [mosch/react-avatar-editor#366]
After cropping the image, there is a gray area around it. Is it possible to hide this? I want to not show the image bleeding outside of the crop area.

**Comment by Minhtality** [comment]
Would love to know this as well. (:

**Comment by nandorojo** [comment]
i got it working - set border to 0 and background to transparent using the props!

**Comment by mosch** [comment]
Hey @nandorojo I'm glad you figured it out! 👏  @Minhtality might this work for you as well?

**Comment by Minhtality** [comment]
> Hey @nandorojo I'm glad you figured it out! 👏 @Minhtality might this work for you as well?

Oh yeah, I just needed to upgrade the package. Was using a pretty outdated version. 🎉
