### ISSUE TITLE
Unable to drag/pan/move the image on mobile

### ISSUE THREAD

**Issue by huumn** [mosch/react-avatar-editor#371]
I tried the demo in Safari and DuckDuckGo browser on iOS, and the chome dev tools mobile simulator thing, and all don't respond to attempts to move the image around.

**Comment by EPecherkin** [comment]
It seems that [this](https://github.com/mosch/react-avatar-editor/blob/main/packages/lib/src/utils/isTouchDevice.ts) code doesn't work properly
It can be fixed with something like [this](https://stackoverflow.com/a/3540295)

**Comment by dan-lee** [comment]
Fixed in `v14.0.0-beta.1` and demo (#375).
