### ISSUE TITLE
How to change background color of Selected area

### ISSUE THREAD

**Issue by vakhariaheet** [mosch/react-avatar-editor#372]
is there any way to change the background colour of the selected area?

**Comment by mosch** [comment]
You can pass `backgroundColor` prop to the component `<AvatarEdtior backgrounColor="#bada55" />`

**Comment by vakhariaheet** [comment]
I want Something like this
<img width="476" alt="image" src="https://user-images.githubusercontent.com/51119569/170650508-b6b9c0ce-3e0e-435f-8f0c-69436105dbaa.png">
Instead colored border I want color overlay

Thanks,

**Comment by mosch** [comment]
Sorry thats not supported. I could think of something like a "tintColor" prop. Or a more generic approach of allowing to manipulate the canvas manually in a callback. PR welcome.
