### ISSUE TITLE
the default width should be 100%

### ISSUE THREAD

**Issue by luisrudge** [mosch/react-avatar-editor#38]

**Comment by luisrudge** [comment]
Let me know when you publish the new version

**Comment by mosch** [comment]
@luisrudge already done!

**Comment by luisrudge** [comment]
Thanks!

**Comment by luisrudge** [comment]
Sorry, but you published a javascript file with ES6 code. It doesn't work anymore.

**Comment by mosch** [comment]
Release version 1.1.2 with es5 code, can you try?

**Comment by luisrudge** [comment]
It works. Great! Thanks!

**Comment by mosch** [comment]
Your welcome! Thanks for feedback :+1:

**Comment by mervick** [comment]
Looks it does not work inside bootstrap columns

![selection_058](https://user-images.githubusercontent.com/2429298/39428670-ed756e9e-4c90-11e8-9f7f-4427d060a186.png)
![selection_059](https://user-images.githubusercontent.com/2429298/39428676-ef8e264e-4c90-11e8-81de-cb6bc53d260d.png)
