### ISSUE TITLE
Is v14 ready for production ?

### ISSUE THREAD

**Issue by jadus** [mosch/react-avatar-editor#383]
Hi,
On v13 i get errors on safari :
TypeError: null is not an object (evaluating 'n.translate') 
context is null...

But on v14 I can't drag the image (on desktop too)

The demo page is on v13 or v14 ?

Thanks

**Comment by MoOx** [comment]
v13 works for me on Safari Version 15.6.1

**Comment by dan-lee** [comment]
The dragging issue should be fixed with `v14.0.0-beta.1`. v14 contains mostly no (breaking) code changes but we simplified the whole build system. The major version/beta is to see if we can catch any problems with that.
