### ISSUE TITLE
TS2307: Cannot find module 'react-avatar-editor' or its corresponding type declarations.

### ISSUE THREAD

**Issue by alexkobylansky** [mosch/react-avatar-editor#393]
"typescript": "^4.5.5",
"react": "^17.0.2",
"react-dom": "^17.0.2",
"@types/react": "^17.0.39",
"@types/react-dom": "^17.0.11",
I add library to devDependencies: "react-avatar-editor": "^13.0.0"
When I try to import the library into a component, Typescript shows a mistake

**Comment by mosch** [comment]
We do provide types now.
