### ISSUE TITLE
Add export-scaling factor

### ISSUE THREAD

**Issue by nmn** [mosch/react-avatar-editor#47]
As of now the editor is mapped to the actual image that will be exported.

It would great if you could edit the image at a resolution that is different from the image that is exported. This is particularly good for things like editing a cover-image. You don't often want to edit the image at it's full size, but you still want to export the cropped version at a high resolution.

**Comment by bluej100** [comment]
#45 seems like a good start on this.

**Comment by nmn** [comment]
@bluej100 does seem like a good start. I can continue the work on it when I get the time.

**Comment by mosch** [comment]
this is fixed with #97
