### ISSUE TITLE
Buggy image scale / drag

### ISSUE THREAD

**Issue by srph** [mosch/react-avatar-editor#51]
![rae](https://cloud.githubusercontent.com/assets/5093058/9033656/c557df50-39fb-11e5-9826-247f6d2b7ece.gif)

It happens when the image is dragged / scaled while its size is lower than the canvas size.

**Comment by mosch** [comment]
Thanks for reporting this! I'll look into this.
@bluej100 do you have an educated guess what's happening here? :)

**Comment by srph** [comment]
Thanks for responding very early :star2:. I'm still digging in the code.

**Comment by bluej100** [comment]
Yeah, it's the BoundedX and Y methods trying to ensure that the selection isn't beyond the boundaries of the image, an impossible constraint here. I'm not sure what the correct behavior would be.

**Comment by bluej100** [comment]
Maybe we could accept an allowBlankSpace option?

**Comment by mosch** [comment]
I think the best is to scale the image up to a minimum of the canvas size. 
So scale=1 is should always fit the canvas size. I'll check what changes need to be made…

**Comment by srph** [comment]
It just happens that when I change the `width` and `height` I pass to `ReactAvatarEditor` (dynamically), the image doesn't resize to fit the canvas.

**Comment by mosch** [comment]
Indeed, this is a valuable information :+1:

**Comment by srph** [comment]
I edited my post, if ever.

**Comment by mosch** [comment]
@srph can u checkout the master and test your use case?

**Comment by srph** [comment]
Alright thanks. I'll try it out :tada:. I have been busy with work these days, sorry to be inactive :confused:.

**Comment by mosch** [comment]
No worries, I'm just back from vacation. Happy to get your feedback ;)

**Comment by srph** [comment]
It's working. Another question, not sure if related: is there any way to move the image around the canvas if it has `<1` scale?

**Comment by mosch** [comment]
Not really. But there is an discussion ongoing in #55, you might want to take part :)
