### ISSUE TITLE
Cross-Origin Resource Sharing policy

### ISSUE THREAD

**Issue by amcmillan01** [mosch/react-avatar-editor#53]
I'm not able to load any image from external url. I'm getting the following error.

```
Image from origin 'http://some.url.com/image.path.png' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost' is therefore not allowed access.
```

Commenting out this line fixed it.
https://github.com/mosch/react-avatar-editor/blob/dcdd4a4a0a8409884c450c1b92490a761419f016/index.js#L116

https://github.com/mosch/react-avatar-editor/blob/master/index.es5.js#L116

**Comment by nickell** [comment]
This worked for me as well. Thanks so much for sharing your solution!

**Comment by nickell** [comment]
I spoke too soon, this caused problems later with editing an image hosted on S3. My particular problem was fixed by properly configuring the CORS settings for my S3 bucket.

**Comment by kraegpoeth** [comment]
@nickell Could help out with how you set up your s3 cors settings?

**Comment by nickell** [comment]
@kraegpoeth Unfortunately that architecture has been torn down in favor of running our infrastructure on digital ocean, so I can't look it up. AWS of course has great docs and I remember using [their CORS guide](http://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html). Hope that helps!
