### ISSUE TITLE
Zoom out issue

### ISSUE THREAD

**Issue by pradeepSEW** [mosch/react-avatar-editor#55]
Is it possible to zoom out as well?

When we are uploading an image of 1000 x 200 size the width of the image is set to show in the editor. Portion of the image is hidden (height wise). I can only shift the image around but now zoom out.

I wish to zoom out at this point to be able to show the entire height of the picture. 

I set the default scale to 5 on a scale of 1 - 10. This did not work either.

Thanks in advance.

**Comment by mosch** [comment]
I think the behaviour you described is intended. You should drag your image around to find the right cutting for the image.
What would be your expected behaviour - or can you describe your use-case a little?

**Comment by sidhacks** [comment]
I have an image that is disproportionately long (tall). When I upload this, it shows up trimmed vertically. 
I wish to zoom out and trim a different region that is taller than the default trim. 

Do you think it'd be possible to set the default slider to the middle and when we slide left we zoom out and when we slide right we zoom in?

**Comment by mosch** [comment]
On of the main ideas of this is not to leave "empty space" on the resulting image. 
So the limit for the zoom out must be when the image in it's height or weight is smaller 
than the height or weight of the editor, it must stop zoom out.
You might consider resizing the editor to fit the image (check onImageLoad prop).
If you really need this, i think we need a prop for enabling and disabling this feature. But i would like to avoid adding this feature, to keep the project small and simple.

**Comment by alexblickenstaff** [comment]
This feature is actually something I'd like. It seems like it should be able to zoom out to the point where sides (or top/bottom) of the image are filled with a background color (which could be another parameter) so that more of the original image can be included. This seems like the natural behavior for when the zoom parameter is set to something less than 1.

**Comment by mtlewis** [comment]
I believe this is already the behaviour - will take a look when I'm at my computer. If so, this issue should be able to be closed.

**Comment by mtlewis** [comment]
We don't currently have the ability to add a background colour to the image, but I've just opened a PR (https://github.com/mosch/react-avatar-editor/pull/195, demo [here](https://deploy-preview-195--react-avatar-editor.netlify.com/)) which adds a checkbox to the demo - you can use this to test the behaviour when the scale is less than 1.

**Comment by alexblickenstaff** [comment]
This looks great!

I'm not sure if there's a simple way to do this, given that the `scale` value can get arbitrarily low, but it seems like it might make sense to limit zooming out such that there can only be "borders" on EITHER the top and bottom OR the left and right. This would mean you couldn't zoom out to the point of the image's longer dimension becoming smaller than the canvas's (which would differ from the current behavior in which you can't zoom out to the point of the image's SHORTER dimension becoming smaller than the canvas's).

The thinking behind this is that it doesn't seem like there's much value in zooming out past that point. The value of zooming out past the shorter dimension is that you're able to fit the entire image in avatar. But I'm not sure what the advantage of zooming out past that would be. At that point you'd effectively just be adding a border around the image.

What are your thoughts?

**Comment by mtlewis** [comment]
Sounds like #149 to me, do you agree?

**Comment by alexblickenstaff** [comment]
Yes, that's describing the same behavior.

**Comment by mtlewis** [comment]
Cool - let's close this in favour of that one :) 

I might try and get a PR up that closes #149 - feel free to submit one yourself though! The maintainers of this component are super welcoming to contributors :D
