### ISSUE TITLE
Validate file type?

### ISSUE THREAD

**Issue by AlexKvazos** [mosch/react-avatar-editor#56]
Is there a way to validate if they are uploading an actual image? I don't want to have to wait till everything reaches the backend to perform the first steps of validation.

**Comment by d-oliveros** [comment]
+1

**Comment by mosch** [comment]
good point. just back from vacation, so give me some time to add this.

I think about adding callback props onUpload, onUploadReady and onUploadFailed.

@dan-lee

**Comment by mosch** [comment]
[released new feature version](https://github.com/mosch/react-avatar-editor/releases/tag/1.4.6)
