### ISSUE TITLE
In chrome dragging the image results in selecting text

### ISSUE THREAD

**Issue by mullwaden** [mosch/react-avatar-editor#57]
Hi,
Whenever i drag the image too far (so the mouse is way outside the area) I start selecting text in chrome. It may be this issue http://stackoverflow.com/questions/2745028/chrome-sets-cursor-to-text-while-dragging-why

**Comment by benwiley4000** [comment]
The fix I implemented for this was to set on the AvatarEditor element, onMouseDown={someFunctionToDisableSelectionForTheWholeParentComponent}, and on the parent component, onMouseUp={someFunctionToReEnableSelection}.

If this were to be implemented into the AvatarEditor itself it would need to receive a prop containing a function bound to the parent component, that triggers a selection disabling change on the parent component.. as well as one to reenable. There could be other good implementations, I just haven't thought of them.

BTW, we enable/disable selection on the parent component by adding/removing a class. the CSS for disabling selection is:

.disable-selection {
    -moz-user-select: none; /* Firefox */
    -ms-user-select: none; /* Internet Explorer */
    -khtml-user-select: none; /* KHTML browsers (e.g. Konqueror) */
    -webkit-user-select: none; /* Chrome, Safari, and Opera */
    -webkit-touch-callout: none; /* Disable Android and iOS callouts*/
}

(Got that from http://sixrevisions.com/css/disable-text-selection/).

**Comment by benwiley4000** [comment]
Update: calling e.preventDefault() on the mousedown handler is apparently enough to fix this. That's included in the new pull request I submitted for a different issue so if accepted this issue should be fixed. https://github.com/mosch/react-avatar-editor/pull/68

**Comment by mosch** [comment]
@benwiley4000 so this is fixed, right?

**Comment by benwiley4000** [comment]
Should be, yep!
