### ISSUE TITLE
React-Overlays

### ISSUE THREAD

**Issue by dozoisch** [mosch/react-avatar-editor#58]
Hello!

Just stumbled on your project and notice it uses react-bootstrap. If you didn't know, we (React-Bootstrap) extracted most of the modal/overlay logic into it's own repo, if that can help you reducing the dependency on RB directly, since you use only a tiny portion!

http://react-bootstrap.github.io/react-overlays/examples/
https://github.com/react-bootstrap/react-overlays

**Comment by mosch** [comment]
no we don't.

**Comment by mosch** [comment]
Hi @dozoisch, thanks for the advice. I don't think we are using react bootstrap at all. 
Is this by accident?  :smile sensitive :no_smoking: times

**Comment by dozoisch** [comment]
@mosch Hmmm I don't know where I saw that... wow! Never mind!
