### ISSUE TITLE
Mouse Drag on a Dell computer with touch screen

### ISSUE THREAD

**Issue by renaudkaczmarek** [mosch/react-avatar-editor#59]
Hello there, 

Great work !
So, I've an issue on my computer. This one has a touch screen.
The result is that when I plug a mouse I can't move the image inside with the cursor but I notced that I can with the touch screen.

I hope you while understand. Sorry for my english :)

**Comment by mosch** [comment]
Thanks for reporting this, we'll look into this.

**Comment by benwiley4000** [comment]
I submitted a pull request that fixes this. https://github.com/mosch/react-avatar-editor/pull/68

**Comment by renaudkaczmarek** [comment]
Nice! Let's test this ;) Thank you!

**Comment by mosch** [comment]
@renaudkaczmarek merged it. did this fix your issue?

**Comment by renaudkaczmarek** [comment]
We didn't test at the moment. I'm waiting for a dev to be available here :) I come back asap!

**Comment by raigfp** [comment]
Dropping still doesn't work in Chrome
@mosch why can't we listen both touch an mouse events in the same time regardless of the "isTouchDevice" like this:
`
        attributes['onMouseDown'] = this.handleMouseDown;
        attributes['onTouchStart'] = this.handleMouseDown;
        
        attributes['onDragOver'] = this.handleDragOver;
        attributes['onTouchMove'] = this.handleDragOver;
        
        attributes['onDrop'] = this.handleDrop;
        attributes['onTouchEnd'] = this.handleDrop;

        return <canvas ref='canvas' {...attributes} />;
`
