### ISSUE TITLE
onUpload never fires

### ISSUE THREAD

**Issue by kokarn** [mosch/react-avatar-editor#60]
Hello! 

I'm playing around with this and it's really nice. There seems to be a bug however as ```onUpload``` never fires. I did this
```js
handleUpload: function(){
  console.log( 'upload' );
}
```

```jsx
<AvatarEditor
  border={ 0 }
  color={ [ 255, 255, 255, 0.6 ] }
  height={ height }
  image={ this.props.image.uri }
  onUpload={ this.handleUpload }
  scale={ scale }
  width={ width }
/>
```
but ```handleUpload``` never fires.

I've looked through the code and either i'm missing something or you forgot to bind the onUpload method when you added it in https://github.com/mosch/react-avatar-editor/commit/01797ece7a0b39d3fce7e10296c355c86d1822e3

I'd write a pull request but for some reason the particular project I'm working on fails to build with browserify when I compile so I can't test it. 

But something like ```this.props.onUpload(e.target.result);``` on [line 314](https://github.com/mosch/react-avatar-editor/blob/master/index.js#L314) should work, right?

**Comment by mosch** [comment]
@kokarn huh. thanks for pointing this out. i'll fix this. ;)

**Comment by kokarn** [comment]
Jay! 
Great news :dancer:

**Comment by hu9o** [comment]
I fail to figure out when onUpload is supposed to fire.
@kokarn what did you expect to trigger onUpload?

**Comment by kokarn** [comment]
Any sort of file upload.

Like https://github.com/mosch/react-avatar-editor/blob/master/index.js#L156 but only when you drag and drop a file, just like the doc says.

My use case was that I want to know when a user drops an image as opposed to the image being set from the prop.

**Comment by hu9o** [comment]
Ok I see, looks like a very simple fix.

However, I think this prop is poorly named, as there is no upload *per se* going on.
"onDropFile" would suit betther IMHO.

**Comment by kokarn** [comment]
Yeah i agree, ```onDropFile``` seems like a better name for it

**Comment by hu9o** [comment]
Added onDropFile: https://github.com/mosch/react-avatar-editor/pull/63
