### ISSUE TITLE
Add automated tests

### ISSUE THREAD

**Issue by hu9o** [mosch/react-avatar-editor#64]
This projects lacks automated tests.
I would like to help but I'm not familiar with tests. Any pointers are appreciated!

**Comment by mosch** [comment]
#44 some test would be nice. 
We could start by adding tests for the file upload events. Have a look at [the test uitls](https://facebook.github.io/react/docs/test-utils.html) and maybe at [how to use jest](https://facebook.github.io/jest/docs/tutorial-react.html)

**Comment by mosch** [comment]
First tests are there. I know we can improve, but I will close this since first tests are there.
