### ISSUE TITLE
Object.assign is not a function

### ISSUE THREAD

**Issue by kicknick** [mosch/react-avatar-editor#67]
Hi! I tried to use this module in my app and stacked with error in browser console: 'Uncaught TypeError: Object.assign is not a function'

Snippet of your code were error happens
Object.assign(defaultStyle,this.props.style)}

**Comment by hu9o** [comment]
Hi,
Some browsers still don't support Object.assign.
Can't read the source right now, but I believe it is used in one single place (added by me :/).
Polyfills exist, but working around it may be a better solution?
