### ISSUE TITLE
Is `calculatePosition` giving out the right x and y?

### ISSUE THREAD

**Issue by chengyin** [mosch/react-avatar-editor#7]
I'm running issues with images being rendered out of bound on the y-axis - the image's y origin will be at the bottom border (max y).

After some tracing I think `calculatePosition` function may be the one that causing the issue. However, since I couldn't figure out what is the intend of the original code, I figured it is better to open an issue instead of the pull request.

I did this change:

```diff
diff --git a/index.js b/index.js
index d75e0e2..3ad6739 100644
--- a/index.js
+++ b/index.js
@@ -120,8 +120,8 @@
                 var lastX = this.state.image.x;
                 var lastY = this.state.image.y;
 
-                var x = Math.round((width  + lastX <= borderX) ? lastX + (borderX - (width  + lastX)) : lastX);
-                var y = Math.round((height + lastY <= borderY) ? lastY + (borderY - (height + lastY)) : lastY);
+                var x = Math.round((height + lastX <= borderX) ? lastX + (borderX - (height + lastX)) : lastX);
+                var y = Math.round((width  + lastY <= borderY) ? lastY + (borderY - (width  + lastY)) : lastY);
 
                 return {
                     x: x,
```

and for my use case this did resolve the bug I saw.

I found it strange that while `borderX` is calculated based on `dimensions.height`, here calculating `x` was done with `width`, instead of `height`.

**Comment by mosch** [comment]
I agree with you that position as the width & height calculation is not clear. I'm working on this and i guess my work will fix your bug too. Want to finish this in the next days, so stay tuned. And thanks for the feedback!

**Comment by mosch** [comment]
Does this problem still happen within your app?

**Comment by ralphie02** [comment]
I am currently using your gem and I think the x-y calculation is incorrect

**Comment by mosch** [comment]
@ralphie02 you realise this when you drag the image? or when you get the cropped image?

**Comment by ralphie02** [comment]
When the image is cropped. I did a workaround by using 0 border and adding an outline on the entire component. Seems to work quite well after that. Awesome gem regardless :+1:

**Comment by mosch** [comment]
@ralphie02 thanks for the report. I'll look into it and see how we can fix this.

**Comment by codedmart** [comment]
@mosch I believe I have fixed the issue, but can't verify and put in a PR until Monday. I have another small fix to PR as well. Thanks for this component.
