### ISSUE TITLE
React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method...

### ISSUE THREAD

**Issue by DDChiang** [mosch/react-avatar-editor#73]
I'm using javascript es5 + react 0.14.0.

I keep getting this warning when I do a simple render for the AvatarEditor component: 

"React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `ImageCropper`."

My code:

    var React = require('react'),
      AvatarEditor = require('react-avatar-editor');
    
     var ImageCropper = React.createClass({
      render: function() {
        return (
            <AvatarEditor
              image="http://example.com/initialimage.jpg"
              width={250}
              height={250}
              border={50}
              color={[255, 255, 255, 0.6]} // RGBA
              scale={1.2} />
        );
      }
    });
    
    module.exports = ImageCropper;

Could anyone tell me what's happening and what I may be doing incorrectly? Really hoping to get started on this :(

**Comment by hu9o** [comment]
``require('react-avatar-editor')`` probably returns ``null``, check that your requiring tool finds react-avatar-editor.

**Comment by jpetitcolas** [comment]
I confirm, this is working fine with React 0.14.3.

**Comment by mosch** [comment]
@DDChiang, i agree with hu9o. Can you check what's inside the *AvatarEditor* var?

**Comment by indeyets** [comment]
I see the same issue. Am getting empty `[object Object]` here.
It worked for us previously, but stopped recently.

Changes I can think of are: babel 5.x -> 6.x, browserify -> webpack2

**Comment by aumayr** [comment]
What didn't work for me, and threw the exception in the title of this issue:

```javascript
import {AvatarEditor} from 'react-avatar-editor';
```

What works:

```javascript
import AvatarEditor from 'react-avatar-editor';
```

**Comment by babsonmatt** [comment]
no luck here either

using ```const AvatarEditor = require('react-avatar-editor');``` or ```import AvatarEditor from 'react-avatar-editor';``` returns an empty object

**Comment by indeyets** [comment]
I solved this issue by bundling CommonJS-source of this module with my project and compiling it locally

**Comment by hanagejet** [comment]
I can't solved...
Help me.

```js
import React, { Component, PropTypes } from 'react';
import AvatarEditor from 'react-avatar-editor';

export class ImageCrop extends Component {

  constructor(props) {
    super(props);
    this.state = {
      scale: 1,
      borderRadius: 0,
      preview: null
    };

    this.handleSave = this.handleSave.bind(this);
    this.handleSave = this.handleSave.bind(this);
    this.handleScale = this.handleScale.bind(this);
    this.handleBorderRadius = this.handleBorderRadius.bind(this);
    this.logCallback = this.logCallback.bind(this);
  }

  getValue () {
    return this.refs.avatar.value;
  }

  handleSave(data) {
      var img = this.refs.avatar.getImage();
      var rect = this.refs.avatar.getCroppingRect();
      this.setState({preview: img, croppingRect: rect});
  }

  handleScale() {
      var scale = parseFloat(this.refs.scale.value);
      this.setState({scale: scale})
  }

  handleBorderRadius() {
      var borderRadius = parseInt(this.refs.borderRadius.value);
      this.setState({borderRadius: borderRadius})
  }

  logCallback(e) {
      console.log("callback", e);
  }

  render() {
    console.log(AvatarEditor);

    return (
        <div>
                <AvatarEditor
                    ref="avatar"
                    scale={this.state.scale}
                    borderRadius={this.state.borderRadius}
                    onSave={this.handleSave}
                    onLoadFailed={this.logCallback.bind(this, 'onLoadFailed')}
                    onUpload={this.logCallback.bind(this, 'onUpload')}
                    onImageLoad={this.logCallback.bind(this, 'onImageLoad')}
                    image="https://fengyuanchen.github.io/cropper/img/picture.jpg"/>
                <br />
                Zoom: <input name="scale" type="range" ref="scale" onChange={this.handleScale} min="1" max="2" step="0.01" defaultValue="1" />
                <br />
                Border radius: <input name="scale" type="range" ref="borderRadius" onChange={this.handleBorderRadius} min="0" max="100" step="1" defaultValue="0" />
                <br />
                <br />
                <input type="button" onClick={this.handleSave} value="Preview" />
                <br />
                <img src={this.state.preview} style={{borderRadius: this.state.borderRadius + 5 /* because of the 5px padding */}} />
            </div>
    );
  }
}

ImageCrop.propTypes = {
  initialValues: PropTypes.string.isRequired,
}

ImageCrop.defaultProps = {
  initialValues: '',
}

export default ImageCrop
```

`console.log(AvatarEditor);` is Object{}...
and it is.
![screen shot 2016-06-08 at 15 28 15](https://cloud.githubusercontent.com/assets/4067007/15884757/99c14dbe-2d8d-11e6-80c1-ec689c527ce1.png)

**Comment by hanagejet** [comment]
maybe dist/index.js is empty.
https://github.com/mosch/react-avatar-editor/blob/1444e9454e392d644972b8b276425c6590fd9b01/dist/index.js

**Comment by mosch** [comment]
@DDChiang is your problem solved right now?

**Comment by ecoukraine** [comment]
Hi guys, 

the same issue

_"Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components)"_

Please, suggest what can be the reason
