### ISSUE TITLE
react 0.14 support ?

### ISSUE THREAD

**Issue by mydearxym** [mosch/react-avatar-editor#78]
amazing work, but react 0.14.x is not support ...
```js
React.findDOMNode is deprecated. Please use ReactDOM.findDOMNode from require('react-dom') instead.
```

**Comment by mosch** [comment]
Thanks for reporting this!

**Comment by mosch** [comment]
This should be fixed in the most recent version: 

https://github.com/mosch/react-avatar-editor/blob/master/index.js

**Comment by mydearxym** [comment]
thinks @mosch  , i install the latest version and it works !
