### ISSUE TITLE
More controllable of border size

### ISSUE THREAD

**Issue by phoenixgao** [mosch/react-avatar-editor#79]
Now it only accept single number and the border with always be square, by looking at facebook avatar editor they have different border-width for top and bottom and left & right.

It could be nice if border option can support an array like
border=all
border=[top, right, bottom, left]
border=[vertical, horizontal]

etc

Thanks

**Comment by SachinJadeja** [comment]
Thanks for the border support of horizontal and vertical.
It would be a great help if you could add support for 
border=[top, right, bottom, left]
