### ISSUE TITLE
Zoom in/out not working on IE10&11

### ISSUE THREAD

**Issue by andreyleonardo** [mosch/react-avatar-editor#84]
After test in some browsers I noticed the only one that is not working is IE (I tried 10 and 11 only).
I was thinking that I could have implemented something wrong but I noticed the same problem in your demo page.

**Comment by mosch** [comment]
Hey, thanks for reporting this!

**Comment by rtirserio** [comment]
The issue is with React and range inputs not raising onChange events in IE. Workaround is to use onMouseUp along with onChange to degrade gracefully.

**Comment by mosch** [comment]
So this is not really a bug in the lib but only in the demo.
