### ISSUE TITLE
onMouseUp() does not do what it should do ?

### ISSUE THREAD

**Issue by willemx** [mosch/react-avatar-editor#86]
The onMouseUp() function should be called whenever the user release the mouse **after interacting with the editor**, but in (my) practice the function is called after every mouseUp event, anywhere in the window, also outside of the editor. This makes the function unusable for what (I think) it is meant for, namely signaling the caller that the image has changed.
Is there a way to change this behaviour, or is there any other way to get a callback whenever the image has changed?

**Comment by mosch** [comment]
We also need to track the mouseup event outside the editor because you might be outside of the area while dragging the image. 
We could think about an 'onImageChange' callback that the editor calls whenever there are changes. I'm curious what you need this for?

**Comment by willemx** [comment]
I need this to be notified whenever the image changes.
I can hack it to work for me if I change this:

``` 
       handleMouseUp: function handleMouseUp() {
            if (this.state.drag) {
                this.setState({ drag: false });
            }
            this.props.onMouseUp();
        }
```
to this:

``` 
       handleMouseUp: function handleMouseUp() {
            if (this.state.drag) {
                this.setState({ drag: false });
                this.props.onMouseUp();
            }
        }
```
Thanks for looking into this!

**Comment by willemx** [comment]
An 'onImageChange' callback would be very nice to have and it could also signal other image-changes like a scale-change.

**Comment by gpbl** [comment]
I'd like an `onImageChange` as well – for example, I would use it to enable/disable the upload button.

**Comment by mosch** [comment]
This should be no problem at all to implement, just add a callback in the end of the paint() method.

**Comment by mosch** [comment]
close. #113 merged
