### ISSUE TITLE
How to clear the image?

### ISSUE THREAD

**Issue by willemx** [mosch/react-avatar-editor#88]
In my UI I need to be able to clear the image. I tried setting the the image prop to null, but this results in a  browser error message:
`modules.js?hash=da04394…:51036 Uncaught TypeError: Cannot read property 'match' of null`

Setting the image prop to an empty string results in a call to 'onLoadFailure'. Is there something I can do in my 'onLoadFailure' function to clear the image?
Or is there another way to clear the image?

**Comment by hu9o** [comment]
I think setting the image prop to an empty string should clear the image.

Since it's not currently the case, I suggest setting the image prop to the **data URL of a 1x1 transparent image**, like this one :

**Comment by willemx** [comment]
Haha, thanks!
I can use this for now, but I hope a more solid solution will eventually be found...
