### ISSUE TITLE
cursor: grab (and grabbing) not supported in webkit

### ISSUE THREAD

**Issue by bbmreed** [mosch/react-avatar-editor#90]
Related to: https://github.com/mosch/react-avatar-editor/pull/62

That change sets `cursor: grab` | `grabbing` which is not supported in webkit, at least.

Might need to add: `-webkit-grab` and `-webkit-grabbing`

**Comment by mosch** [comment]
this can be solved by using something like radium. 
sadly there is no easy fix for that.

**Comment by mb21** [comment]
Since this cannot be fixed in the inline style attribute due to https://github.com/facebook/react/issues/6467, I've resolved to using the following CSS:

```
  canvas {
    cursor: move; /* fallback if grab cursor is unsupported */
    cursor: -webkit-grab;
    cursor: -moz-grab;
    cursor: grab;
  }
  canvas:active {
    cursor: -webkit-grabbing;
    cursor: -moz-grabbing;
    cursor: grabbing;
  }
```
